# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Emile Silvis
tagline:          'Some thoughts'
description:      'Thoughts (mostly on making software)'
baseurl:          https://emilesilvis.github.io/

author:
  name:           'Emile Silvis'
  url:            https://twitter.com/emilesilvis

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
