// GENERATED by search/campaign-search.mjs — regenerate, do not hand-edit.
// Every level below was found by exhaustive machine search: the reference
// build is the smallest solving machine the instrument found, and the
// walkthrough quotes the measurements taken at generation time.

export const CAMPAIGN = [
  {
    "id": "campaign-etude-1",
    "title": "Étude I",
    "chapter": "I · Études",
    "assignment": "Every seed carries 1 stray note at the head, and every target ends in C. Blind parts only — no reading yet.",
    "board": {
      "cols": 9,
      "rows": 5
    },
    "fixed": [
      {
        "id": "q1",
        "kind": "quill",
        "x": 1,
        "y": 1
      },
      {
        "id": "r1",
        "kind": "resonator",
        "x": 7,
        "y": 1
      }
    ],
    "palette": {
      "mould": 2,
      "damper": 2
    },
    "cases": [
      {
        "name": "Aria",
        "seeds": {
          "q1": "DAB"
        },
        "targets": {
          "r1": "ABC"
        }
      },
      {
        "name": "Encore",
        "seeds": {
          "q1": "DBA"
        },
        "targets": {
          "r1": "BAC"
        }
      },
      {
        "name": "Coda",
        "seeds": {
          "q1": "DBB"
        },
        "targets": {
          "r1": "BBC"
        }
      }
    ],
    "reference": {
      "parts": [
        {
          "id": "p0",
          "kind": "mould",
          "config": {
            "note": "C"
          },
          "x": 3,
          "y": 1
        },
        {
          "id": "p1",
          "kind": "damper",
          "config": {},
          "x": 5,
          "y": 1
        }
      ],
      "wires": [
        {
          "from": {
            "part": "q1",
            "port": "out"
          },
          "to": {
            "part": "p0",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "out"
          },
          "to": {
            "part": "p1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "out"
          },
          "to": {
            "part": "r1",
            "port": "in"
          }
        }
      ]
    },
    "meta": {
      "minParts": 2,
      "familiesAtMin": 2,
      "familiesCapped": false,
      "forced": [
        "mould",
        "damper"
      ]
    },
    "walkthrough": [
      {
        "focus": "commission",
        "title": "I · Études",
        "body": "Blind parts only: moulds sing onto the tail, dampers take from the head. A string is a queue — that asymmetry is the whole chapter. 3 performances: every hall with a printed target must ring, a hall marked “stay silent” must not, and one machine serves them all."
      },
      {
        "focus": "board",
        "title": "A nudge",
        "body": "One part takes from the head, one sings onto the tail. Wire them in a line — and try both orders before you believe order matters here."
      },
      {
        "focus": "board",
        "title": "What the search measured — spoilers",
        "body": "The smallest solving machine uses 2 parts, and at that size the instrument found 2 structurally different builds. No build exists without: mould, damper. Find any one of them — the reference is only the smallest."
      }
    ]
  },
  {
    "id": "campaign-etude-3",
    "title": "Étude II",
    "chapter": "I · Études",
    "assignment": "Every target is the seed with C·D sung onto the tail. Blind parts only.",
    "board": {
      "cols": 9,
      "rows": 5
    },
    "fixed": [
      {
        "id": "q1",
        "kind": "quill",
        "x": 1,
        "y": 1
      },
      {
        "id": "r1",
        "kind": "resonator",
        "x": 7,
        "y": 1
      }
    ],
    "palette": {
      "mould": 2,
      "damper": 2
    },
    "cases": [
      {
        "name": "Aria",
        "seeds": {
          "q1": "A"
        },
        "targets": {
          "r1": "ACD"
        }
      },
      {
        "name": "Encore",
        "seeds": {
          "q1": "BA"
        },
        "targets": {
          "r1": "BACD"
        }
      },
      {
        "name": "Coda",
        "seeds": {
          "q1": "DBA"
        },
        "targets": {
          "r1": "DBACD"
        }
      }
    ],
    "reference": {
      "parts": [
        {
          "id": "p0",
          "kind": "mould",
          "config": {
            "note": "C"
          },
          "x": 3,
          "y": 1
        },
        {
          "id": "p1",
          "kind": "mould",
          "config": {
            "note": "D"
          },
          "x": 5,
          "y": 1
        }
      ],
      "wires": [
        {
          "from": {
            "part": "q1",
            "port": "out"
          },
          "to": {
            "part": "p0",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "out"
          },
          "to": {
            "part": "p1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "out"
          },
          "to": {
            "part": "r1",
            "port": "in"
          }
        }
      ]
    },
    "meta": {
      "minParts": 2,
      "familiesAtMin": 1,
      "familiesCapped": false,
      "forced": [
        "mould"
      ]
    },
    "walkthrough": [
      {
        "focus": "commission",
        "title": "I · Études",
        "body": "Blind parts only: moulds sing onto the tail, dampers take from the head. A string is a queue — that asymmetry is the whole chapter. 3 performances: every hall with a printed target must ring, a hall marked “stay silent” must not, and one machine serves them all."
      },
      {
        "focus": "board",
        "title": "A nudge",
        "body": "Nothing needs taking away. Two singers — and the order they stand in is the order the tail reads."
      },
      {
        "focus": "board",
        "title": "What the search measured — spoilers",
        "body": "The smallest solving machine uses 2 parts, and at that size the instrument found 1 structurally different build. No build exists without: mould. Find any one of them — the reference is only the smallest."
      }
    ]
  },
  {
    "id": "campaign-etude-2",
    "title": "Étude III",
    "chapter": "I · Études",
    "assignment": "Every seed carries 2 stray notes at the head, and every target ends in B. Blind parts only — no reading yet.",
    "board": {
      "cols": 11,
      "rows": 5
    },
    "fixed": [
      {
        "id": "q1",
        "kind": "quill",
        "x": 1,
        "y": 1
      },
      {
        "id": "r1",
        "kind": "resonator",
        "x": 9,
        "y": 1
      }
    ],
    "palette": {
      "mould": 2,
      "damper": 2
    },
    "cases": [
      {
        "name": "Aria",
        "seeds": {
          "q1": "CDAA"
        },
        "targets": {
          "r1": "AAB"
        }
      },
      {
        "name": "Encore",
        "seeds": {
          "q1": "CDDA"
        },
        "targets": {
          "r1": "DAB"
        }
      },
      {
        "name": "Coda",
        "seeds": {
          "q1": "CDAD"
        },
        "targets": {
          "r1": "ADB"
        }
      }
    ],
    "reference": {
      "parts": [
        {
          "id": "p0",
          "kind": "mould",
          "config": {
            "note": "B"
          },
          "x": 3,
          "y": 1
        },
        {
          "id": "p1",
          "kind": "damper",
          "config": {},
          "x": 5,
          "y": 1
        },
        {
          "id": "p2",
          "kind": "damper",
          "config": {},
          "x": 7,
          "y": 1
        }
      ],
      "wires": [
        {
          "from": {
            "part": "q1",
            "port": "out"
          },
          "to": {
            "part": "p0",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "out"
          },
          "to": {
            "part": "p1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "out"
          },
          "to": {
            "part": "p2",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p2",
            "port": "out"
          },
          "to": {
            "part": "r1",
            "port": "in"
          }
        }
      ]
    },
    "meta": {
      "minParts": 3,
      "familiesAtMin": 3,
      "familiesCapped": false,
      "forced": [
        "mould",
        "damper"
      ]
    },
    "walkthrough": [
      {
        "focus": "commission",
        "title": "I · Études",
        "body": "Blind parts only: moulds sing onto the tail, dampers take from the head. A string is a queue — that asymmetry is the whole chapter. 3 performances: every hall with a printed target must ring, a hall marked “stay silent” must not, and one machine serves them all."
      },
      {
        "focus": "board",
        "title": "A nudge",
        "body": "A damper takes exactly one head note per pass. Two stray notes means the string must meet a damper twice."
      },
      {
        "focus": "board",
        "title": "What the search measured — spoilers",
        "body": "The smallest solving machine uses 3 parts, and at that size the instrument found 3 structurally different builds. No build exists without: mould, damper. Find any one of them — the reference is only the smallest."
      }
    ]
  },
  {
    "id": "campaign-etude-4",
    "title": "Étude IV",
    "chapter": "I · Études",
    "assignment": "Every seed carries 1 stray note at the head, and every target ends in D·C. Blind parts only — no reading yet.",
    "board": {
      "cols": 11,
      "rows": 5
    },
    "fixed": [
      {
        "id": "q1",
        "kind": "quill",
        "x": 1,
        "y": 1
      },
      {
        "id": "r1",
        "kind": "resonator",
        "x": 9,
        "y": 1
      }
    ],
    "palette": {
      "mould": 2,
      "damper": 2
    },
    "cases": [
      {
        "name": "Aria",
        "seeds": {
          "q1": "BAB"
        },
        "targets": {
          "r1": "ABDC"
        }
      },
      {
        "name": "Encore",
        "seeds": {
          "q1": "BBA"
        },
        "targets": {
          "r1": "BADC"
        }
      },
      {
        "name": "Coda",
        "seeds": {
          "q1": "BBB"
        },
        "targets": {
          "r1": "BBDC"
        }
      }
    ],
    "reference": {
      "parts": [
        {
          "id": "p0",
          "kind": "mould",
          "config": {
            "note": "C"
          },
          "x": 5,
          "y": 1
        },
        {
          "id": "p1",
          "kind": "mould",
          "config": {
            "note": "D"
          },
          "x": 3,
          "y": 1
        },
        {
          "id": "p2",
          "kind": "damper",
          "config": {},
          "x": 7,
          "y": 1
        }
      ],
      "wires": [
        {
          "from": {
            "part": "q1",
            "port": "out"
          },
          "to": {
            "part": "p1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "out"
          },
          "to": {
            "part": "p2",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "out"
          },
          "to": {
            "part": "p0",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p2",
            "port": "out"
          },
          "to": {
            "part": "r1",
            "port": "in"
          }
        }
      ]
    },
    "meta": {
      "minParts": 3,
      "familiesAtMin": 3,
      "familiesCapped": false,
      "forced": [
        "mould",
        "damper"
      ]
    },
    "walkthrough": [
      {
        "focus": "commission",
        "title": "I · Études",
        "body": "Blind parts only: moulds sing onto the tail, dampers take from the head. A string is a queue — that asymmetry is the whole chapter. 3 performances: every hall with a printed target must ring, a hall marked “stay silent” must not, and one machine serves them all."
      },
      {
        "focus": "board",
        "title": "A nudge",
        "body": "Three jobs in one line: one take, two songs. The target’s LAST note names the LAST singer."
      },
      {
        "focus": "board",
        "title": "What the search measured — spoilers",
        "body": "The smallest solving machine uses 3 parts, and at that size the instrument found 3 structurally different builds. No build exists without: mould, damper. Find any one of them — the reference is only the smallest."
      }
    ]
  },
  {
    "id": "campaign-duet-merge-stamp",
    "title": "Duet I — merge and stamp",
    "chapter": "II · Duets",
    "assignment": "Two voices become one, then the mould signs it. Seat order matters.",
    "board": {
      "cols": 9,
      "rows": 5
    },
    "fixed": [
      {
        "id": "q1",
        "kind": "quill",
        "label": "first voice",
        "x": 1,
        "y": 1
      },
      {
        "id": "q2",
        "kind": "quill",
        "label": "second voice",
        "x": 1,
        "y": 3
      },
      {
        "id": "r1",
        "kind": "resonator",
        "x": 7,
        "y": 1
      }
    ],
    "palette": {
      "unison": 1,
      "splitter": 1,
      "mould": 1,
      "damper": 1
    },
    "cases": [
      {
        "name": "Aria",
        "seeds": {
          "q1": "AB",
          "q2": "DA"
        },
        "targets": {
          "r1": "ABDAC"
        }
      },
      {
        "name": "Encore",
        "seeds": {
          "q1": "BD",
          "q2": "AB"
        },
        "targets": {
          "r1": "BDABC"
        }
      }
    ],
    "reference": {
      "parts": [
        {
          "id": "p0",
          "kind": "unison",
          "config": {},
          "x": 3,
          "y": 1
        },
        {
          "id": "p1",
          "kind": "mould",
          "config": {
            "note": "C"
          },
          "x": 5,
          "y": 1
        }
      ],
      "wires": [
        {
          "from": {
            "part": "q1",
            "port": "out"
          },
          "to": {
            "part": "p0",
            "port": "lead"
          }
        },
        {
          "from": {
            "part": "q2",
            "port": "out"
          },
          "to": {
            "part": "p0",
            "port": "tail"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "out"
          },
          "to": {
            "part": "p1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "out"
          },
          "to": {
            "part": "r1",
            "port": "in"
          }
        }
      ]
    },
    "meta": {
      "minParts": 2,
      "familiesAtMin": 2,
      "familiesCapped": false,
      "forced": [
        "unison",
        "mould"
      ]
    },
    "walkthrough": [
      {
        "focus": "commission",
        "title": "II · Duets",
        "body": "Nothing here reads a note. Cuts land at a count and joins follow seat order — these commissions are about structure, not content. 2 performances: every hall with a printed target must ring, a hall marked “stay silent” must not, and one machine serves them all."
      },
      {
        "focus": "board",
        "title": "A nudge",
        "body": "The signature belongs to the finished duet, not to one voice. What does that force about the order of joining and signing?"
      },
      {
        "focus": "board",
        "title": "What the search measured — spoilers",
        "body": "The smallest solving machine uses 2 parts, and at that size the instrument found 2 structurally different builds. No build exists without: unison, mould. Find any one of them — the reference is only the smallest."
      }
    ]
  },
  {
    "id": "campaign-duet-swap",
    "title": "Duet II — the swap",
    "chapter": "II · Duets",
    "assignment": "The target is the seed with its halves exchanged. Nothing here reads a note: the cut is at a count, and the rejoin is a seating order.",
    "board": {
      "cols": 9,
      "rows": 5
    },
    "fixed": [
      {
        "id": "q1",
        "kind": "quill",
        "x": 1,
        "y": 1
      },
      {
        "id": "r1",
        "kind": "resonator",
        "x": 7,
        "y": 1
      }
    ],
    "palette": {
      "unison": 1,
      "splitter": 1,
      "mould": 1,
      "damper": 1
    },
    "cases": [
      {
        "name": "Aria",
        "seeds": {
          "q1": "ABCD"
        },
        "targets": {
          "r1": "CDAB"
        }
      },
      {
        "name": "Encore",
        "seeds": {
          "q1": "DDBA"
        },
        "targets": {
          "r1": "BADD"
        }
      }
    ],
    "reference": {
      "parts": [
        {
          "id": "p0",
          "kind": "unison",
          "config": {},
          "x": 5,
          "y": 1
        },
        {
          "id": "p1",
          "kind": "splitter",
          "config": {
            "k": 2
          },
          "x": 3,
          "y": 1
        }
      ],
      "wires": [
        {
          "from": {
            "part": "q1",
            "port": "out"
          },
          "to": {
            "part": "p1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "out"
          },
          "to": {
            "part": "r1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "head"
          },
          "to": {
            "part": "p0",
            "port": "tail"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "rest"
          },
          "to": {
            "part": "p0",
            "port": "lead"
          }
        }
      ]
    },
    "meta": {
      "minParts": 2,
      "familiesAtMin": 1,
      "familiesCapped": false,
      "forced": [
        "unison",
        "splitter"
      ]
    },
    "walkthrough": [
      {
        "focus": "commission",
        "title": "II · Duets",
        "body": "Nothing here reads a note. Cuts land at a count and joins follow seat order — these commissions are about structure, not content. 2 performances: every hall with a printed target must ring, a hall marked “stay silent” must not, and one machine serves them all."
      },
      {
        "focus": "board",
        "title": "A nudge",
        "body": "To trade halves you must first have halves — and a rejoin seats them in whichever order you choose."
      },
      {
        "focus": "board",
        "title": "What the search measured — spoilers",
        "body": "The smallest solving machine uses 2 parts, and at that size the instrument found 1 structurally different build. No build exists without: unison, splitter. Find any one of them — the reference is only the smallest."
      }
    ]
  },
  {
    "id": "campaign-duet-insert",
    "title": "Duet III — the graft",
    "chapter": "II · Duets",
    "assignment": "A note appears in the MIDDLE of the word. No part writes anywhere but the tail — so the string must come apart.",
    "board": {
      "cols": 9,
      "rows": 5
    },
    "fixed": [
      {
        "id": "q1",
        "kind": "quill",
        "x": 1,
        "y": 1
      },
      {
        "id": "r1",
        "kind": "resonator",
        "x": 7,
        "y": 1
      }
    ],
    "palette": {
      "unison": 1,
      "splitter": 1,
      "mould": 1,
      "damper": 1
    },
    "cases": [
      {
        "name": "Aria",
        "seeds": {
          "q1": "ABCA"
        },
        "targets": {
          "r1": "ABDCA"
        }
      },
      {
        "name": "Encore",
        "seeds": {
          "q1": "CBAD"
        },
        "targets": {
          "r1": "CBDAD"
        }
      }
    ],
    "reference": {
      "parts": [
        {
          "id": "p0",
          "kind": "unison",
          "config": {},
          "x": 5,
          "y": 1
        },
        {
          "id": "p1",
          "kind": "splitter",
          "config": {
            "k": 2
          },
          "x": 3,
          "y": 1
        },
        {
          "id": "p2",
          "kind": "mould",
          "config": {
            "note": "D"
          },
          "x": 5,
          "y": 3
        }
      ],
      "wires": [
        {
          "from": {
            "part": "q1",
            "port": "out"
          },
          "to": {
            "part": "p1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "out"
          },
          "to": {
            "part": "r1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "head"
          },
          "to": {
            "part": "p2",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "rest"
          },
          "to": {
            "part": "p0",
            "port": "tail"
          }
        },
        {
          "from": {
            "part": "p2",
            "port": "out"
          },
          "to": {
            "part": "p0",
            "port": "lead"
          }
        }
      ]
    },
    "meta": {
      "minParts": 3,
      "familiesAtMin": 1,
      "familiesCapped": false,
      "forced": [
        "unison",
        "splitter",
        "mould"
      ]
    },
    "walkthrough": [
      {
        "focus": "commission",
        "title": "II · Duets",
        "body": "Nothing here reads a note. Cuts land at a count and joins follow seat order — these commissions are about structure, not content. 2 performances: every hall with a printed target must ring, a hall marked “stay silent” must not, and one machine serves them all."
      },
      {
        "focus": "board",
        "title": "A nudge",
        "body": "No part writes in the middle. But the middle of one string is the seam between two shorter ones."
      },
      {
        "focus": "board",
        "title": "What the search measured — spoilers",
        "body": "The smallest solving machine uses 3 parts, and at that size the instrument found 1 structurally different build. No build exists without: unison, splitter, mould. Find any one of them — the reference is only the smallest."
      }
    ]
  },
  {
    "id": "campaign-duet-behead",
    "title": "Duet IV — beheaded harmony",
    "chapter": "II · Duets",
    "assignment": "The second voice loses its head before the voices join.",
    "board": {
      "cols": 9,
      "rows": 5
    },
    "fixed": [
      {
        "id": "q1",
        "kind": "quill",
        "label": "first voice",
        "x": 1,
        "y": 1
      },
      {
        "id": "q2",
        "kind": "quill",
        "label": "second voice",
        "x": 1,
        "y": 3
      },
      {
        "id": "r1",
        "kind": "resonator",
        "x": 5,
        "y": 1
      }
    ],
    "palette": {
      "unison": 1,
      "splitter": 1,
      "mould": 1,
      "damper": 1
    },
    "cases": [
      {
        "name": "Aria",
        "seeds": {
          "q1": "AB",
          "q2": "DCA"
        },
        "targets": {
          "r1": "ABCA"
        }
      },
      {
        "name": "Encore",
        "seeds": {
          "q1": "CA",
          "q2": "BDD"
        },
        "targets": {
          "r1": "CADD"
        }
      }
    ],
    "reference": {
      "parts": [
        {
          "id": "p0",
          "kind": "unison",
          "config": {},
          "x": 3,
          "y": 1
        },
        {
          "id": "p1",
          "kind": "damper",
          "config": {},
          "x": 3,
          "y": 3
        }
      ],
      "wires": [
        {
          "from": {
            "part": "q1",
            "port": "out"
          },
          "to": {
            "part": "p0",
            "port": "lead"
          }
        },
        {
          "from": {
            "part": "q2",
            "port": "out"
          },
          "to": {
            "part": "p1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "out"
          },
          "to": {
            "part": "r1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "out"
          },
          "to": {
            "part": "p0",
            "port": "tail"
          }
        }
      ]
    },
    "meta": {
      "minParts": 2,
      "familiesAtMin": 1,
      "familiesCapped": false,
      "forced": [
        "unison",
        "damper"
      ]
    },
    "walkthrough": [
      {
        "focus": "commission",
        "title": "II · Duets",
        "body": "Nothing here reads a note. Cuts land at a count and joins follow seat order — these commissions are about structure, not content. 2 performances: every hall with a printed target must ring, a hall marked “stay silent” must not, and one machine serves them all."
      },
      {
        "focus": "board",
        "title": "A nudge",
        "body": "Only one voice loses its head — damp it before the seats, not after."
      },
      {
        "focus": "board",
        "title": "What the search measured — spoilers",
        "body": "The smallest solving machine uses 2 parts, and at that size the instrument found 1 structurally different build. No build exists without: unison, damper. Find any one of them — the reference is only the smallest."
      }
    ]
  },
  {
    "id": "campaign-reading-stamps",
    "title": "Sight-reading I — two signatures",
    "chapter": "III · Sight-reading",
    "assignment": "The head note names the hall, and each hall wants its own signature sung on the tail. A pipe cannot do this.",
    "board": {
      "cols": 9,
      "rows": 5
    },
    "fixed": [
      {
        "id": "q1",
        "kind": "quill",
        "x": 1,
        "y": 1
      },
      {
        "id": "r1",
        "kind": "resonator",
        "label": "hall of A",
        "x": 7,
        "y": 1
      },
      {
        "id": "r2",
        "kind": "resonator",
        "label": "hall of B",
        "x": 7,
        "y": 3
      }
    ],
    "palette": {
      "fork": 2,
      "mould": 2
    },
    "cases": [
      {
        "name": "Aria",
        "seeds": {
          "q1": "ACB"
        },
        "targets": {
          "r1": "ACBD"
        }
      },
      {
        "name": "Encore",
        "seeds": {
          "q1": "BCB"
        },
        "targets": {
          "r2": "BCBC"
        }
      }
    ],
    "reference": {
      "parts": [
        {
          "id": "p0",
          "kind": "fork",
          "config": {
            "note": "A",
            "mode": "peek"
          },
          "x": 3,
          "y": 1
        },
        {
          "id": "p1",
          "kind": "mould",
          "config": {
            "note": "C"
          },
          "x": 5,
          "y": 1
        },
        {
          "id": "p2",
          "kind": "mould",
          "config": {
            "note": "D"
          },
          "x": 5,
          "y": 3
        }
      ],
      "wires": [
        {
          "from": {
            "part": "q1",
            "port": "out"
          },
          "to": {
            "part": "p0",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "left"
          },
          "to": {
            "part": "p2",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "right"
          },
          "to": {
            "part": "p1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "out"
          },
          "to": {
            "part": "r2",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p2",
            "port": "out"
          },
          "to": {
            "part": "r1",
            "port": "in"
          }
        }
      ]
    },
    "meta": {
      "minParts": 3,
      "familiesAtMin": 2,
      "familiesCapped": false,
      "forced": [
        "fork",
        "mould"
      ]
    },
    "walkthrough": [
      {
        "focus": "commission",
        "title": "III · Sight-reading",
        "body": "The fork reads the head and routes. From here on the performances disagree, and a machine that cannot read cannot serve them all. 2 performances: every hall with a printed target must ring, a hall marked “stay silent” must not, and one machine serves them all."
      },
      {
        "focus": "board",
        "title": "A nudge",
        "body": "The halls want different signatures, so the singing must happen after the parting. What decides the parting?"
      },
      {
        "focus": "board",
        "title": "What the search measured — spoilers",
        "body": "The smallest solving machine uses 3 parts, and at that size the instrument found 2 structurally different builds. No build exists without: fork, mould. Find any one of them — the reference is only the smallest."
      }
    ]
  },
  {
    "id": "campaign-reading-threeway",
    "title": "Sight-reading II — three halls",
    "chapter": "III · Sight-reading",
    "assignment": "Three openings, three halls, one machine. One fork has two exits; the commission has three.",
    "board": {
      "cols": 9,
      "rows": 7
    },
    "fixed": [
      {
        "id": "q1",
        "kind": "quill",
        "x": 1,
        "y": 1
      },
      {
        "id": "r1",
        "kind": "resonator",
        "label": "hall of A",
        "x": 7,
        "y": 1
      },
      {
        "id": "r2",
        "kind": "resonator",
        "label": "hall of B",
        "x": 7,
        "y": 3
      },
      {
        "id": "r3",
        "kind": "resonator",
        "label": "hall of C",
        "x": 7,
        "y": 5
      }
    ],
    "palette": {
      "fork": 2,
      "mould": 2
    },
    "cases": [
      {
        "name": "Aria",
        "seeds": {
          "q1": "AD"
        },
        "targets": {
          "r1": "AD"
        }
      },
      {
        "name": "Encore",
        "seeds": {
          "q1": "BD"
        },
        "targets": {
          "r2": "BD"
        }
      },
      {
        "name": "Coda",
        "seeds": {
          "q1": "CD"
        },
        "targets": {
          "r3": "CD"
        }
      }
    ],
    "reference": {
      "parts": [
        {
          "id": "p0",
          "kind": "fork",
          "config": {
            "note": "A",
            "mode": "peek"
          },
          "x": 3,
          "y": 1
        },
        {
          "id": "p1",
          "kind": "fork",
          "config": {
            "note": "B",
            "mode": "peek"
          },
          "x": 5,
          "y": 1
        }
      ],
      "wires": [
        {
          "from": {
            "part": "q1",
            "port": "out"
          },
          "to": {
            "part": "p0",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "left"
          },
          "to": {
            "part": "r1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "right"
          },
          "to": {
            "part": "p1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "left"
          },
          "to": {
            "part": "r2",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "right"
          },
          "to": {
            "part": "r3",
            "port": "in"
          }
        }
      ]
    },
    "meta": {
      "minParts": 2,
      "familiesAtMin": 6,
      "familiesCapped": false,
      "forced": [
        "fork"
      ]
    },
    "walkthrough": [
      {
        "focus": "commission",
        "title": "III · Sight-reading",
        "body": "The fork reads the head and routes. From here on the performances disagree, and a machine that cannot read cannot serve them all. 3 performances: every hall with a printed target must ring, a hall marked “stay silent” must not, and one machine serves them all."
      },
      {
        "focus": "board",
        "title": "A nudge",
        "body": "One fork knows two ways. The third way is whatever falls through — so where does the second fork listen?"
      },
      {
        "focus": "board",
        "title": "What the search measured — spoilers",
        "body": "The smallest solving machine uses 2 parts, and at that size the instrument found 6 structurally different builds. No build exists without: fork. Find any one of them — the reference is only the smallest."
      }
    ]
  },
  {
    "id": "campaign-wolf-strip-stamp",
    "title": "Wolf I — bitten clean, then signed",
    "chapter": "IV · Wolf notes",
    "assignment": "Strip every leading A — the count differs per performance — then sign the result. The loop does the counting.",
    "board": {
      "cols": 9,
      "rows": 5
    },
    "fixed": [
      {
        "id": "q1",
        "kind": "quill",
        "x": 1,
        "y": 1
      },
      {
        "id": "r1",
        "kind": "resonator",
        "x": 7,
        "y": 1
      }
    ],
    "palette": {
      "fork": 2,
      "mould": 1,
      "damper": 1
    },
    "cases": [
      {
        "name": "Aria",
        "seeds": {
          "q1": "AAB"
        },
        "targets": {
          "r1": "BC"
        }
      },
      {
        "name": "Encore",
        "seeds": {
          "q1": "AB"
        },
        "targets": {
          "r1": "BC"
        }
      },
      {
        "name": "Coda",
        "seeds": {
          "q1": "B"
        },
        "targets": {
          "r1": "BC"
        }
      }
    ],
    "reference": {
      "parts": [
        {
          "id": "p0",
          "kind": "fork",
          "config": {
            "note": "A",
            "mode": "consume"
          },
          "x": 3,
          "y": 1
        },
        {
          "id": "p1",
          "kind": "mould",
          "config": {
            "note": "C"
          },
          "x": 5,
          "y": 1
        }
      ],
      "wires": [
        {
          "from": {
            "part": "q1",
            "port": "out"
          },
          "to": {
            "part": "p0",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "left"
          },
          "to": {
            "part": "p0",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "right"
          },
          "to": {
            "part": "p1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "out"
          },
          "to": {
            "part": "r1",
            "port": "in"
          }
        }
      ]
    },
    "meta": {
      "minParts": 2,
      "familiesAtMin": 2,
      "familiesCapped": false,
      "forced": [
        "fork",
        "mould"
      ]
    },
    "walkthrough": [
      {
        "focus": "commission",
        "title": "IV · Wolf notes",
        "body": "A bite in a loop: each pass takes one head note, and the string itself decides how many passes. The read does the counting. 3 performances: every hall with a printed target must ring, a hall marked “stay silent” must not, and one machine serves them all."
      },
      {
        "focus": "board",
        "title": "A nudge",
        "body": "A bite takes one A. The performances disagree about how many — so the same fork must see the string again."
      },
      {
        "focus": "board",
        "title": "What the search measured — spoilers",
        "body": "The smallest solving machine uses 2 parts, and at that size the instrument found 2 structurally different builds. No build exists without: fork, mould. Find any one of them — the reference is only the smallest."
      }
    ]
  },
  {
    "id": "campaign-wolf-rotate",
    "title": "Wolf II — the rotation",
    "chapter": "IV · Wolf notes",
    "assignment": "Leading A’s do not vanish — they move to the tail. A bite and a mould, holding hands in a loop.",
    "board": {
      "cols": 9,
      "rows": 5
    },
    "fixed": [
      {
        "id": "q1",
        "kind": "quill",
        "x": 1,
        "y": 1
      },
      {
        "id": "r1",
        "kind": "resonator",
        "x": 7,
        "y": 1
      }
    ],
    "palette": {
      "fork": 2,
      "mould": 1,
      "damper": 1
    },
    "cases": [
      {
        "name": "Aria",
        "seeds": {
          "q1": "AAB"
        },
        "targets": {
          "r1": "BAA"
        }
      },
      {
        "name": "Encore",
        "seeds": {
          "q1": "AB"
        },
        "targets": {
          "r1": "BA"
        }
      },
      {
        "name": "Coda",
        "seeds": {
          "q1": "BB"
        },
        "targets": {
          "r1": "BB"
        }
      }
    ],
    "reference": {
      "parts": [
        {
          "id": "p0",
          "kind": "fork",
          "config": {
            "note": "A",
            "mode": "consume"
          },
          "x": 3,
          "y": 1
        },
        {
          "id": "p1",
          "kind": "mould",
          "config": {
            "note": "A"
          },
          "x": 5,
          "y": 1
        }
      ],
      "wires": [
        {
          "from": {
            "part": "q1",
            "port": "out"
          },
          "to": {
            "part": "p0",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "left"
          },
          "to": {
            "part": "p1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "right"
          },
          "to": {
            "part": "r1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "out"
          },
          "to": {
            "part": "p0",
            "port": "in"
          }
        }
      ]
    },
    "meta": {
      "minParts": 2,
      "familiesAtMin": 1,
      "familiesCapped": false,
      "forced": [
        "fork",
        "mould"
      ]
    },
    "walkthrough": [
      {
        "focus": "commission",
        "title": "IV · Wolf notes",
        "body": "A bite in a loop: each pass takes one head note, and the string itself decides how many passes. The read does the counting. 3 performances: every hall with a printed target must ring, a hall marked “stay silent” must not, and one machine serves them all."
      },
      {
        "focus": "board",
        "title": "A nudge",
        "body": "What the bite takes from the head, a mould can restore at the tail — if the loop carries the string through both."
      },
      {
        "focus": "board",
        "title": "What the search measured — spoilers",
        "body": "The smallest solving machine uses 2 parts, and at that size the instrument found 1 structurally different build. No build exists without: fork, mould. Find any one of them — the reference is only the smallest."
      }
    ]
  },
  {
    "id": "campaign-wolf-two-teeth",
    "title": "Wolf III — two teeth",
    "chapter": "IV · Wolf notes",
    "assignment": "Strip the leading A’s, then the leading B’s. Two loops, or one very clever one.",
    "board": {
      "cols": 9,
      "rows": 5
    },
    "fixed": [
      {
        "id": "q1",
        "kind": "quill",
        "x": 1,
        "y": 1
      },
      {
        "id": "r1",
        "kind": "resonator",
        "x": 7,
        "y": 1
      }
    ],
    "palette": {
      "fork": 2,
      "mould": 1,
      "damper": 1
    },
    "cases": [
      {
        "name": "Aria",
        "seeds": {
          "q1": "AABC"
        },
        "targets": {
          "r1": "C"
        }
      },
      {
        "name": "Encore",
        "seeds": {
          "q1": "ABBC"
        },
        "targets": {
          "r1": "C"
        }
      },
      {
        "name": "Coda",
        "seeds": {
          "q1": "BC"
        },
        "targets": {
          "r1": "C"
        }
      },
      {
        "name": "Reprise",
        "seeds": {
          "q1": "ABAC"
        },
        "targets": {
          "r1": "AC"
        }
      }
    ],
    "reference": {
      "parts": [
        {
          "id": "p0",
          "kind": "fork",
          "config": {
            "note": "A",
            "mode": "consume"
          },
          "x": 3,
          "y": 1
        },
        {
          "id": "p1",
          "kind": "fork",
          "config": {
            "note": "B",
            "mode": "consume"
          },
          "x": 5,
          "y": 1
        }
      ],
      "wires": [
        {
          "from": {
            "part": "q1",
            "port": "out"
          },
          "to": {
            "part": "p0",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "left"
          },
          "to": {
            "part": "p0",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "right"
          },
          "to": {
            "part": "p1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "left"
          },
          "to": {
            "part": "p1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "right"
          },
          "to": {
            "part": "r1",
            "port": "in"
          }
        }
      ]
    },
    "meta": {
      "minParts": 2,
      "familiesAtMin": 1,
      "familiesCapped": false,
      "forced": [
        "fork"
      ]
    },
    "walkthrough": [
      {
        "focus": "commission",
        "title": "IV · Wolf notes",
        "body": "A bite in a loop: each pass takes one head note, and the string itself decides how many passes. The read does the counting. 4 performances: every hall with a printed target must ring, a hall marked “stay silent” must not, and one machine serves them all."
      },
      {
        "focus": "board",
        "title": "A nudge",
        "body": "Strip the A’s, hand the result on, strip the B’s. Ask what tells each loop it is finished — and check the Reprise before you trust your answer."
      },
      {
        "focus": "board",
        "title": "What the search measured — spoilers",
        "body": "The smallest solving machine uses 2 parts, and at that size the instrument found 1 structurally different build. No build exists without: fork. Find any one of them — the reference is only the smallest."
      }
    ]
  },
  {
    "id": "campaign-tangle-stamped-gate",
    "title": "Entanglement I — the stamped gate",
    "chapter": "V · Entanglements",
    "assignment": "The label routes the payload, and the A-lane signs what passes through it. The label itself retires to the bin.",
    "board": {
      "cols": 9,
      "rows": 7
    },
    "fixed": [
      {
        "id": "q1",
        "kind": "quill",
        "label": "the label",
        "x": 1,
        "y": 1
      },
      {
        "id": "q2",
        "kind": "quill",
        "label": "the payload",
        "x": 1,
        "y": 3
      },
      {
        "id": "r1",
        "kind": "resonator",
        "label": "spent labels",
        "x": 7,
        "y": 1
      },
      {
        "id": "r2",
        "kind": "resonator",
        "label": "hall of A",
        "x": 7,
        "y": 3
      },
      {
        "id": "r3",
        "kind": "resonator",
        "label": "hall of B",
        "x": 7,
        "y": 5
      }
    ],
    "palette": {
      "coupling": 1,
      "mould": 1,
      "damper": 1
    },
    "cases": [
      {
        "name": "Aria",
        "seeds": {
          "q1": "A",
          "q2": "CD"
        },
        "targets": {
          "r1": "A",
          "r2": "CDD"
        }
      },
      {
        "name": "Encore",
        "seeds": {
          "q1": "B",
          "q2": "CD"
        },
        "targets": {
          "r1": "B",
          "r3": "CD"
        }
      }
    ],
    "reference": {
      "parts": [
        {
          "id": "p0",
          "kind": "coupling",
          "config": {
            "noteA": "A",
            "noteB": "A"
          },
          "x": 3,
          "y": 1
        },
        {
          "id": "p1",
          "kind": "mould",
          "config": {
            "note": "D"
          },
          "x": 5,
          "y": 1
        }
      ],
      "wires": [
        {
          "from": {
            "part": "q1",
            "port": "out"
          },
          "to": {
            "part": "p0",
            "port": "inA"
          }
        },
        {
          "from": {
            "part": "q2",
            "port": "out"
          },
          "to": {
            "part": "p0",
            "port": "inB"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "outAR"
          },
          "to": {
            "part": "r1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "outBL"
          },
          "to": {
            "part": "p1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "outBR"
          },
          "to": {
            "part": "r3",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "out"
          },
          "to": {
            "part": "r2",
            "port": "in"
          }
        }
      ]
    },
    "meta": {
      "minParts": 2,
      "familiesAtMin": 2,
      "familiesCapped": true,
      "forced": [
        "coupling",
        "mould"
      ]
    },
    "walkthrough": [
      {
        "focus": "commission",
        "title": "V · Entanglements",
        "body": "The coupling holds two strings until both arrive, then routes each by the OTHER one’s head. Nobody routes themselves. 2 performances: every hall with a printed target must ring, a hall marked “stay silent” must not, and one machine serves them all."
      },
      {
        "focus": "board",
        "title": "A nudge",
        "body": "Which seat holds the string being routed, and which holds the string that decides? The coupling reads across, not along."
      },
      {
        "focus": "board",
        "title": "What the search measured — spoilers",
        "body": "The smallest solving machine uses 2 parts, and at that size the instrument found at least 2 structurally different builds. No build exists without: coupling, mould. Find any one of them — the reference is only the smallest."
      }
    ]
  },
  {
    "id": "campaign-tangle-mutual",
    "title": "Entanglement II — mutual regard",
    "chapter": "V · Entanglements",
    "assignment": "Two voices, and each one’s exit is decided by the other’s opening note. Nobody routes themselves.",
    "board": {
      "cols": 9,
      "rows": 9
    },
    "fixed": [
      {
        "id": "q1",
        "kind": "quill",
        "label": "first voice",
        "x": 1,
        "y": 1
      },
      {
        "id": "q2",
        "kind": "quill",
        "label": "second voice",
        "x": 1,
        "y": 3
      },
      {
        "id": "r1",
        "kind": "resonator",
        "label": "first hall",
        "x": 5,
        "y": 1
      },
      {
        "id": "r2",
        "kind": "resonator",
        "label": "first annex",
        "x": 5,
        "y": 3
      },
      {
        "id": "r3",
        "kind": "resonator",
        "label": "second hall",
        "x": 5,
        "y": 5
      },
      {
        "id": "r4",
        "kind": "resonator",
        "label": "second annex",
        "x": 5,
        "y": 7
      }
    ],
    "palette": {
      "coupling": 1,
      "mould": 1,
      "damper": 1
    },
    "cases": [
      {
        "name": "Aria",
        "seeds": {
          "q1": "AB",
          "q2": "AD"
        },
        "targets": {
          "r1": "AB",
          "r3": "AD"
        }
      },
      {
        "name": "Encore",
        "seeds": {
          "q1": "BB",
          "q2": "AD"
        },
        "targets": {
          "r1": "BB",
          "r4": "AD"
        }
      },
      {
        "name": "Coda",
        "seeds": {
          "q1": "BD",
          "q2": "CB"
        },
        "targets": {
          "r2": "BD",
          "r4": "CB"
        }
      }
    ],
    "reference": {
      "parts": [
        {
          "id": "p0",
          "kind": "coupling",
          "config": {
            "noteA": "A",
            "noteB": "A"
          },
          "x": 3,
          "y": 1
        }
      ],
      "wires": [
        {
          "from": {
            "part": "q1",
            "port": "out"
          },
          "to": {
            "part": "p0",
            "port": "inA"
          }
        },
        {
          "from": {
            "part": "q2",
            "port": "out"
          },
          "to": {
            "part": "p0",
            "port": "inB"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "outAL"
          },
          "to": {
            "part": "r1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "outAR"
          },
          "to": {
            "part": "r2",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "outBL"
          },
          "to": {
            "part": "r3",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "outBR"
          },
          "to": {
            "part": "r4",
            "port": "in"
          }
        }
      ]
    },
    "meta": {
      "minParts": 1,
      "familiesAtMin": 8,
      "familiesCapped": false,
      "forced": [
        "coupling"
      ]
    },
    "walkthrough": [
      {
        "focus": "commission",
        "title": "V · Entanglements",
        "body": "The coupling holds two strings until both arrive, then routes each by the OTHER one’s head. Nobody routes themselves. 3 performances: every hall with a printed target must ring, a hall marked “stay silent” must not, and one machine serves them all."
      },
      {
        "focus": "board",
        "title": "A nudge",
        "body": "One part, four exits — and each voice’s test note is about the OTHER voice. Set both notes, then walk one performance by hand."
      },
      {
        "focus": "board",
        "title": "What the search measured — spoilers",
        "body": "The smallest solving machine uses 1 part, and at that size the instrument found 8 structurally different builds. No build exists without: coupling. Find any one of them — the reference is only the smallest."
      }
    ]
  },
  {
    "id": "campaign-tempo-cross",
    "title": "Tempo II — the crossed duet",
    "chapter": "VI · Tempo",
    "assignment": "Four voices, two seats, two products — and the near pairs are the wrong pairs. Hold one voice until the far ones are seated.",
    "board": {
      "cols": 9,
      "rows": 9
    },
    "fixed": [
      {
        "id": "q1",
        "kind": "quill",
        "label": "B — near",
        "x": 1,
        "y": 1
      },
      {
        "id": "q2",
        "kind": "quill",
        "label": "A — far",
        "x": 1,
        "y": 3
      },
      {
        "id": "q3",
        "kind": "quill",
        "label": "near tail",
        "x": 1,
        "y": 5
      },
      {
        "id": "q4",
        "kind": "quill",
        "label": "far tail",
        "x": 1,
        "y": 7
      },
      {
        "id": "r1",
        "kind": "resonator",
        "label": "hall of A",
        "x": 7,
        "y": 1
      },
      {
        "id": "r2",
        "kind": "resonator",
        "label": "the other hall",
        "x": 7,
        "y": 3
      }
    ],
    "palette": {
      "valve": 1,
      "unison": 1,
      "fork": 1
    },
    "cases": [
      {
        "name": "Aria",
        "seeds": {
          "q1": "B",
          "q2": "A",
          "q3": "C",
          "q4": "D"
        },
        "targets": {
          "r1": "AC",
          "r2": "BD"
        }
      },
      {
        "name": "Encore",
        "seeds": {
          "q1": "B",
          "q2": "A",
          "q3": "D",
          "q4": "C"
        },
        "targets": {
          "r1": "AD",
          "r2": "BC"
        }
      }
    ],
    "reference": {
      "parts": [
        {
          "id": "p0",
          "kind": "valve",
          "config": {
            "delay": 1
          },
          "x": 3,
          "y": 1
        },
        {
          "id": "p1",
          "kind": "unison",
          "config": {},
          "x": 3,
          "y": 3
        },
        {
          "id": "p2",
          "kind": "fork",
          "config": {
            "note": "A",
            "mode": "peek"
          },
          "x": 5,
          "y": 1
        }
      ],
      "wires": [
        {
          "from": {
            "part": "q1",
            "port": "out"
          },
          "to": {
            "part": "p0",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "q2",
            "port": "out"
          },
          "to": {
            "part": "p1",
            "port": "lead"
          }
        },
        {
          "from": {
            "part": "q3",
            "port": "out"
          },
          "to": {
            "part": "p1",
            "port": "tail"
          }
        },
        {
          "from": {
            "part": "q4",
            "port": "out"
          },
          "to": {
            "part": "p1",
            "port": "tail"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "out"
          },
          "to": {
            "part": "p1",
            "port": "lead"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "out"
          },
          "to": {
            "part": "p2",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p2",
            "port": "left"
          },
          "to": {
            "part": "r1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p2",
            "port": "right"
          },
          "to": {
            "part": "r2",
            "port": "in"
          }
        }
      ]
    },
    "meta": {
      "minParts": 3,
      "familiesAtMin": 6,
      "familiesCapped": true,
      "forced": [
        "unison",
        "fork"
      ],
      "valveAtLayout": true
    },
    "walkthrough": [
      {
        "focus": "commission",
        "title": "VI · Tempo",
        "body": "Distance is delay: every wire chip is travel time, and a valve is travel time you can hold in one cell. These commissions are races for a shared seat. 2 performances: every hall with a printed target must ring, a hall marked “stay silent” must not, and one machine serves them all."
      },
      {
        "focus": "board",
        "title": "A nudge",
        "body": "Run it bare and read the event log: who reaches each seat first? Then decide which single path must be slower, and by how much."
      },
      {
        "focus": "board",
        "title": "What the search measured — spoilers",
        "body": "The smallest solving machine uses 3 parts, and at that size the instrument found at least 6 structurally different builds. No build exists without: unison, fork. At the search’s own placement, no machine without the valve solved this — but distance is delay, and your geometry is your own. Find any one of them — the reference is only the smallest."
      }
    ]
  },
  {
    "id": "campaign-concerto-envelope",
    "title": "Concerto I — the envelope",
    "chapter": "VII · Concerto",
    "assignment": "One string arrives: a one-note header sealed onto a body. Open it, let the header route its own body, and file the header away.",
    "board": {
      "cols": 9,
      "rows": 7
    },
    "fixed": [
      {
        "id": "q1",
        "kind": "quill",
        "x": 1,
        "y": 1
      },
      {
        "id": "r1",
        "kind": "resonator",
        "label": "spent headers",
        "x": 7,
        "y": 1
      },
      {
        "id": "r2",
        "kind": "resonator",
        "label": "hall of A",
        "x": 7,
        "y": 3
      },
      {
        "id": "r3",
        "kind": "resonator",
        "label": "hall of B",
        "x": 7,
        "y": 5
      }
    ],
    "palette": {
      "splitter": 1,
      "coupling": 1,
      "mould": 1,
      "damper": 1
    },
    "cases": [
      {
        "name": "Aria",
        "seeds": {
          "q1": "ACD"
        },
        "targets": {
          "r1": "A",
          "r2": "CD"
        }
      },
      {
        "name": "Encore",
        "seeds": {
          "q1": "BCD"
        },
        "targets": {
          "r1": "B",
          "r3": "CD"
        }
      },
      {
        "name": "Coda",
        "seeds": {
          "q1": "ADD"
        },
        "targets": {
          "r1": "A",
          "r2": "DD"
        }
      }
    ],
    "reference": {
      "parts": [
        {
          "id": "p0",
          "kind": "splitter",
          "config": {
            "k": 1
          },
          "x": 3,
          "y": 1
        },
        {
          "id": "p1",
          "kind": "coupling",
          "config": {
            "noteA": "A",
            "noteB": "A"
          },
          "x": 5,
          "y": 1
        }
      ],
      "wires": [
        {
          "from": {
            "part": "q1",
            "port": "out"
          },
          "to": {
            "part": "p0",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "head"
          },
          "to": {
            "part": "p1",
            "port": "inA"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "rest"
          },
          "to": {
            "part": "p1",
            "port": "inB"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "outAR"
          },
          "to": {
            "part": "r1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "outBL"
          },
          "to": {
            "part": "r2",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "outBR"
          },
          "to": {
            "part": "r3",
            "port": "in"
          }
        }
      ]
    },
    "meta": {
      "minParts": 2,
      "familiesAtMin": 8,
      "familiesCapped": true,
      "forced": [
        "splitter",
        "coupling"
      ]
    },
    "walkthrough": [
      {
        "focus": "commission",
        "title": "VII · Concerto",
        "body": "Everything at once — cuts, reads, loops, crossed reads. The commissions grow, and so must the machine. 3 performances: every hall with a printed target must ring, a hall marked “stay silent” must not, and one machine serves them all."
      },
      {
        "focus": "board",
        "title": "A nudge",
        "body": "Cut first — after the cut, the header is exactly the string that knows where its own body belongs."
      },
      {
        "focus": "board",
        "title": "What the search measured — spoilers",
        "body": "The smallest solving machine uses 2 parts, and at that size the instrument found at least 8 structurally different builds. No build exists without: splitter, coupling. Find any one of them — the reference is only the smallest."
      }
    ]
  },
  {
    "id": "campaign-concerto-signed",
    "title": "Concerto II — the signed envelope",
    "chapter": "VII · Concerto",
    "assignment": "The envelope again, but the hall of A only accepts bodies signed with its own note.",
    "board": {
      "cols": 11,
      "rows": 7
    },
    "fixed": [
      {
        "id": "q1",
        "kind": "quill",
        "x": 1,
        "y": 1
      },
      {
        "id": "r1",
        "kind": "resonator",
        "label": "spent headers",
        "x": 9,
        "y": 1
      },
      {
        "id": "r2",
        "kind": "resonator",
        "label": "hall of A",
        "x": 9,
        "y": 3
      },
      {
        "id": "r3",
        "kind": "resonator",
        "label": "hall of B",
        "x": 9,
        "y": 5
      }
    ],
    "palette": {
      "splitter": 1,
      "coupling": 1,
      "mould": 1
    },
    "cases": [
      {
        "name": "Aria",
        "seeds": {
          "q1": "ACD"
        },
        "targets": {
          "r1": "A",
          "r2": "CDA"
        }
      },
      {
        "name": "Encore",
        "seeds": {
          "q1": "BCD"
        },
        "targets": {
          "r1": "B",
          "r3": "CD"
        }
      },
      {
        "name": "Coda",
        "seeds": {
          "q1": "ADC"
        },
        "targets": {
          "r1": "A",
          "r2": "DCA"
        }
      }
    ],
    "reference": {
      "parts": [
        {
          "id": "p0",
          "kind": "splitter",
          "config": {
            "k": 1
          },
          "x": 3,
          "y": 1
        },
        {
          "id": "p1",
          "kind": "coupling",
          "config": {
            "noteA": "A",
            "noteB": "A"
          },
          "x": 5,
          "y": 1
        },
        {
          "id": "p2",
          "kind": "mould",
          "config": {
            "note": "A"
          },
          "x": 7,
          "y": 1
        }
      ],
      "wires": [
        {
          "from": {
            "part": "q1",
            "port": "out"
          },
          "to": {
            "part": "p0",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "head"
          },
          "to": {
            "part": "p1",
            "port": "inA"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "rest"
          },
          "to": {
            "part": "p1",
            "port": "inB"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "outAR"
          },
          "to": {
            "part": "r1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "outBL"
          },
          "to": {
            "part": "p2",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "outBR"
          },
          "to": {
            "part": "r3",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p2",
            "port": "out"
          },
          "to": {
            "part": "r2",
            "port": "in"
          }
        }
      ]
    },
    "meta": {
      "minParts": 3,
      "familiesAtMin": 8,
      "familiesCapped": true,
      "forced": [
        "splitter",
        "coupling",
        "mould"
      ]
    },
    "walkthrough": [
      {
        "focus": "commission",
        "title": "VII · Concerto",
        "body": "Everything at once — cuts, reads, loops, crossed reads. The commissions grow, and so must the machine. 3 performances: every hall with a printed target must ring, a hall marked “stay silent” must not, and one machine serves them all."
      },
      {
        "focus": "board",
        "title": "A nudge",
        "body": "The envelope again — but now one lane signs its bodies. Sign after the routing, or the wrong hall inherits the signature."
      },
      {
        "focus": "board",
        "title": "What the search measured — spoilers",
        "body": "The smallest solving machine uses 3 parts, and at that size the instrument found at least 8 structurally different builds. No build exists without: splitter, coupling, mould. Find any one of them — the reference is only the smallest."
      }
    ]
  },
  {
    "id": "campaign-concerto-wolf",
    "title": "Concerto III — the wolf’s commission",
    "chapter": "VII · Concerto",
    "assignment": "Strip the leading A’s — the count differs per performance — then let the note that emerges name the hall, and sign each hall’s strings with that hall’s own signature.",
    "board": {
      "cols": 11,
      "rows": 5
    },
    "fixed": [
      {
        "id": "q1",
        "kind": "quill",
        "x": 1,
        "y": 1
      },
      {
        "id": "r1",
        "kind": "resonator",
        "label": "hall of B",
        "x": 9,
        "y": 1
      },
      {
        "id": "r2",
        "kind": "resonator",
        "label": "hall of C",
        "x": 9,
        "y": 3
      }
    ],
    "palette": {
      "fork": 2,
      "mould": 2
    },
    "cases": [
      {
        "name": "Aria",
        "seeds": {
          "q1": "AABC"
        },
        "targets": {
          "r1": "BCC"
        }
      },
      {
        "name": "Encore",
        "seeds": {
          "q1": "ACB"
        },
        "targets": {
          "r2": "CBB"
        }
      },
      {
        "name": "Coda",
        "seeds": {
          "q1": "BC"
        },
        "targets": {
          "r1": "BCC"
        }
      },
      {
        "name": "Reprise",
        "seeds": {
          "q1": "CB"
        },
        "targets": {
          "r2": "CBB"
        }
      }
    ],
    "reference": {
      "parts": [
        {
          "id": "p0",
          "kind": "fork",
          "config": {
            "note": "A",
            "mode": "consume"
          },
          "x": 3,
          "y": 1
        },
        {
          "id": "p1",
          "kind": "fork",
          "config": {
            "note": "B",
            "mode": "peek"
          },
          "x": 5,
          "y": 1
        },
        {
          "id": "p2",
          "kind": "mould",
          "config": {
            "note": "B"
          },
          "x": 7,
          "y": 1
        },
        {
          "id": "p3",
          "kind": "mould",
          "config": {
            "note": "C"
          },
          "x": 7,
          "y": 3
        }
      ],
      "wires": [
        {
          "from": {
            "part": "q1",
            "port": "out"
          },
          "to": {
            "part": "p0",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "left"
          },
          "to": {
            "part": "p0",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "right"
          },
          "to": {
            "part": "p1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "left"
          },
          "to": {
            "part": "p3",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "right"
          },
          "to": {
            "part": "p2",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p2",
            "port": "out"
          },
          "to": {
            "part": "r2",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p3",
            "port": "out"
          },
          "to": {
            "part": "r1",
            "port": "in"
          }
        }
      ]
    },
    "meta": {
      "minParts": 4,
      "familiesAtMin": 4,
      "familiesCapped": false,
      "forced": [
        "fork",
        "mould"
      ]
    },
    "walkthrough": [
      {
        "focus": "commission",
        "title": "VII · Concerto",
        "body": "Everything at once — cuts, reads, loops, crossed reads. The commissions grow, and so must the machine. 4 performances: every hall with a printed target must ring, a hall marked “stay silent” must not, and one machine serves them all."
      },
      {
        "focus": "board",
        "title": "A nudge",
        "body": "Strip, read, sign. One of those happens in a loop, one happens once, and one must happen differently per hall."
      },
      {
        "focus": "board",
        "title": "What the search measured — spoilers",
        "body": "The smallest solving machine uses 4 parts, and at that size the instrument found 4 structurally different builds. No build exists without: fork, mould. Find any one of them — the reference is only the smallest."
      }
    ]
  },
];
