// GENERATED by search/campaign-search.mjs: regenerate, do not hand-edit.
// Every level below was found by exhaustive machine search: the reference
// build is the smallest solving machine the instrument found, and the
// walkthrough quotes the measurements taken at generation time.

export const CAMPAIGN = [
  {
    "id": "campaign-etude-1",
    "title": "Étude I",
    "chapter": "I · Études",
    "assignment": "Remove 1 note from the beginning of each seed, then append C. Do not use a fork.",
    "board": {
      "cols": 9,
      "rows": 5
    },
    "fixed": [
      {
        "id": "q1",
        "kind": "quill",
        "x": 1,
        "y": 1
      },
      {
        "id": "r1",
        "kind": "resonator",
        "x": 7,
        "y": 1
      }
    ],
    "palette": {
      "mould": 2,
      "damper": 2
    },
    "cases": [
      {
        "name": "Aria",
        "seeds": {
          "q1": "DAB"
        },
        "targets": {
          "r1": "ABC"
        }
      },
      {
        "name": "Encore",
        "seeds": {
          "q1": "DBA"
        },
        "targets": {
          "r1": "BAC"
        }
      },
      {
        "name": "Coda",
        "seeds": {
          "q1": "DBB"
        },
        "targets": {
          "r1": "BBC"
        }
      }
    ],
    "reference": {
      "parts": [
        {
          "id": "p0",
          "kind": "mould",
          "config": {
            "note": "C"
          },
          "x": 3,
          "y": 1
        },
        {
          "id": "p1",
          "kind": "damper",
          "config": {},
          "x": 5,
          "y": 1
        }
      ],
      "wires": [
        {
          "from": {
            "part": "q1",
            "port": "out"
          },
          "to": {
            "part": "p0",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "out"
          },
          "to": {
            "part": "p1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "out"
          },
          "to": {
            "part": "r1",
            "port": "in"
          }
        }
      ]
    },
    "meta": {
      "minParts": 2,
      "signaturesAtMin": 2,
      "signaturesCapped": false,
      "forced": [
        "mould",
        "damper"
      ]
    },
    "walkthrough": [
      {
        "focus": "commission",
        "title": "I · Études",
        "body": "Moulds append notes, and dampers remove first notes. These parts do not inspect the word. Use one machine for all 3 performances. Each resonator must receive its target word; resonators marked “stay silent” must receive nothing."
      },
      {
        "focus": "board",
        "title": "A nudge",
        "body": "Place one damper and one mould in a line. Test both possible orders."
      },
      {
        "focus": "board",
        "title": "Search results: spoilers",
        "body": "Minimum: 2 parts. The search found 2 labelled layouts at that size. Required parts: mould, damper. Different layouts can represent the same approach. The reference is one minimum solution."
      }
    ]
  },
  {
    "id": "campaign-etude-3",
    "title": "Étude II",
    "chapter": "I · Études",
    "assignment": "Append C·D to each seed. Do not use a fork.",
    "board": {
      "cols": 9,
      "rows": 5
    },
    "fixed": [
      {
        "id": "q1",
        "kind": "quill",
        "x": 1,
        "y": 1
      },
      {
        "id": "r1",
        "kind": "resonator",
        "x": 7,
        "y": 1
      }
    ],
    "palette": {
      "mould": 2,
      "damper": 2
    },
    "cases": [
      {
        "name": "Aria",
        "seeds": {
          "q1": "A"
        },
        "targets": {
          "r1": "ACD"
        }
      },
      {
        "name": "Encore",
        "seeds": {
          "q1": "BA"
        },
        "targets": {
          "r1": "BACD"
        }
      },
      {
        "name": "Coda",
        "seeds": {
          "q1": "DBA"
        },
        "targets": {
          "r1": "DBACD"
        }
      }
    ],
    "reference": {
      "parts": [
        {
          "id": "p0",
          "kind": "mould",
          "config": {
            "note": "C"
          },
          "x": 3,
          "y": 1
        },
        {
          "id": "p1",
          "kind": "mould",
          "config": {
            "note": "D"
          },
          "x": 5,
          "y": 1
        }
      ],
      "wires": [
        {
          "from": {
            "part": "q1",
            "port": "out"
          },
          "to": {
            "part": "p0",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "out"
          },
          "to": {
            "part": "p1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "out"
          },
          "to": {
            "part": "r1",
            "port": "in"
          }
        }
      ]
    },
    "meta": {
      "minParts": 2,
      "signaturesAtMin": 1,
      "signaturesCapped": false,
      "forced": [
        "mould"
      ]
    },
    "walkthrough": [
      {
        "focus": "commission",
        "title": "I · Études",
        "body": "Moulds append notes, and dampers remove first notes. These parts do not inspect the word. Use one machine for all 3 performances. Each resonator must receive its target word; resonators marked “stay silent” must receive nothing."
      },
      {
        "focus": "board",
        "title": "A nudge",
        "body": "Use two moulds. Their order determines the final two notes."
      },
      {
        "focus": "board",
        "title": "Search results: spoilers",
        "body": "Minimum: 2 parts. The search found 1 labelled layout at that size. Required parts: mould. Different layouts can represent the same approach. The reference is one minimum solution."
      }
    ]
  },
  {
    "id": "campaign-etude-2",
    "title": "Étude III",
    "chapter": "I · Études",
    "assignment": "Remove 2 notes from the beginning of each seed, then append B. Do not use a fork.",
    "board": {
      "cols": 11,
      "rows": 5
    },
    "fixed": [
      {
        "id": "q1",
        "kind": "quill",
        "x": 1,
        "y": 1
      },
      {
        "id": "r1",
        "kind": "resonator",
        "x": 9,
        "y": 1
      }
    ],
    "palette": {
      "mould": 2,
      "damper": 2
    },
    "cases": [
      {
        "name": "Aria",
        "seeds": {
          "q1": "CDAA"
        },
        "targets": {
          "r1": "AAB"
        }
      },
      {
        "name": "Encore",
        "seeds": {
          "q1": "CDDA"
        },
        "targets": {
          "r1": "DAB"
        }
      },
      {
        "name": "Coda",
        "seeds": {
          "q1": "CDAD"
        },
        "targets": {
          "r1": "ADB"
        }
      }
    ],
    "reference": {
      "parts": [
        {
          "id": "p0",
          "kind": "mould",
          "config": {
            "note": "B"
          },
          "x": 3,
          "y": 1
        },
        {
          "id": "p1",
          "kind": "damper",
          "config": {},
          "x": 5,
          "y": 1
        },
        {
          "id": "p2",
          "kind": "damper",
          "config": {},
          "x": 7,
          "y": 1
        }
      ],
      "wires": [
        {
          "from": {
            "part": "q1",
            "port": "out"
          },
          "to": {
            "part": "p0",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "out"
          },
          "to": {
            "part": "p1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "out"
          },
          "to": {
            "part": "p2",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p2",
            "port": "out"
          },
          "to": {
            "part": "r1",
            "port": "in"
          }
        }
      ]
    },
    "meta": {
      "minParts": 3,
      "signaturesAtMin": 3,
      "signaturesCapped": false,
      "forced": [
        "mould",
        "damper"
      ]
    },
    "walkthrough": [
      {
        "focus": "commission",
        "title": "I · Études",
        "body": "Moulds append notes, and dampers remove first notes. These parts do not inspect the word. Use one machine for all 3 performances. Each resonator must receive its target word; resonators marked “stay silent” must receive nothing."
      },
      {
        "focus": "board",
        "title": "A nudge",
        "body": "A damper takes exactly one head note per pass. Two stray notes means the string must meet a damper twice."
      },
      {
        "focus": "board",
        "title": "Search results: spoilers",
        "body": "Minimum: 3 parts. The search found 3 labelled layouts at that size. Required parts: mould, damper. Different layouts can represent the same approach. The reference is one minimum solution."
      }
    ]
  },
  {
    "id": "campaign-etude-4",
    "title": "Étude IV",
    "chapter": "I · Études",
    "assignment": "Remove 1 note from the beginning of each seed, then append D·C. Do not use a fork.",
    "board": {
      "cols": 11,
      "rows": 5
    },
    "fixed": [
      {
        "id": "q1",
        "kind": "quill",
        "x": 1,
        "y": 1
      },
      {
        "id": "r1",
        "kind": "resonator",
        "x": 9,
        "y": 1
      }
    ],
    "palette": {
      "mould": 2,
      "damper": 2
    },
    "cases": [
      {
        "name": "Aria",
        "seeds": {
          "q1": "BAB"
        },
        "targets": {
          "r1": "ABDC"
        }
      },
      {
        "name": "Encore",
        "seeds": {
          "q1": "BBA"
        },
        "targets": {
          "r1": "BADC"
        }
      },
      {
        "name": "Coda",
        "seeds": {
          "q1": "BBB"
        },
        "targets": {
          "r1": "BBDC"
        }
      }
    ],
    "reference": {
      "parts": [
        {
          "id": "p0",
          "kind": "mould",
          "config": {
            "note": "C"
          },
          "x": 5,
          "y": 1
        },
        {
          "id": "p1",
          "kind": "mould",
          "config": {
            "note": "D"
          },
          "x": 3,
          "y": 1
        },
        {
          "id": "p2",
          "kind": "damper",
          "config": {},
          "x": 7,
          "y": 1
        }
      ],
      "wires": [
        {
          "from": {
            "part": "q1",
            "port": "out"
          },
          "to": {
            "part": "p1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "out"
          },
          "to": {
            "part": "p2",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "out"
          },
          "to": {
            "part": "p0",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p2",
            "port": "out"
          },
          "to": {
            "part": "r1",
            "port": "in"
          }
        }
      ]
    },
    "meta": {
      "minParts": 3,
      "signaturesAtMin": 3,
      "signaturesCapped": false,
      "forced": [
        "mould",
        "damper"
      ]
    },
    "walkthrough": [
      {
        "focus": "commission",
        "title": "I · Études",
        "body": "Moulds append notes, and dampers remove first notes. These parts do not inspect the word. Use one machine for all 3 performances. Each resonator must receive its target word; resonators marked “stay silent” must receive nothing."
      },
      {
        "focus": "board",
        "title": "A nudge",
        "body": "Place one damper followed by two moulds. Put the C mould last because the target ends in C."
      },
      {
        "focus": "board",
        "title": "Search results: spoilers",
        "body": "Minimum: 3 parts. The search found 3 labelled layouts at that size. Required parts: mould, damper. Different layouts can represent the same approach. The reference is one minimum solution."
      }
    ]
  },
  {
    "id": "campaign-duet-merge-stamp",
    "title": "Duet I: merge and stamp",
    "chapter": "II · Duets",
    "assignment": "Join the two seed words in order, then append C.",
    "board": {
      "cols": 9,
      "rows": 5
    },
    "fixed": [
      {
        "id": "q1",
        "kind": "quill",
        "label": "first voice",
        "x": 1,
        "y": 1
      },
      {
        "id": "q2",
        "kind": "quill",
        "label": "second voice",
        "x": 1,
        "y": 3
      },
      {
        "id": "r1",
        "kind": "resonator",
        "x": 7,
        "y": 1
      }
    ],
    "palette": {
      "unison": 1,
      "splitter": 1,
      "mould": 1,
      "damper": 1
    },
    "cases": [
      {
        "name": "Aria",
        "seeds": {
          "q1": "AB",
          "q2": "DA"
        },
        "targets": {
          "r1": "ABDAC"
        }
      },
      {
        "name": "Encore",
        "seeds": {
          "q1": "BD",
          "q2": "AB"
        },
        "targets": {
          "r1": "BDABC"
        }
      }
    ],
    "reference": {
      "parts": [
        {
          "id": "p0",
          "kind": "unison",
          "config": {},
          "x": 3,
          "y": 1
        },
        {
          "id": "p1",
          "kind": "mould",
          "config": {
            "note": "C"
          },
          "x": 5,
          "y": 1
        }
      ],
      "wires": [
        {
          "from": {
            "part": "q1",
            "port": "out"
          },
          "to": {
            "part": "p0",
            "port": "lead"
          }
        },
        {
          "from": {
            "part": "q2",
            "port": "out"
          },
          "to": {
            "part": "p0",
            "port": "tail"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "out"
          },
          "to": {
            "part": "p1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "out"
          },
          "to": {
            "part": "r1",
            "port": "in"
          }
        }
      ]
    },
    "meta": {
      "minParts": 2,
      "signaturesAtMin": 2,
      "signaturesCapped": false,
      "forced": [
        "unison",
        "mould"
      ]
    },
    "walkthrough": [
      {
        "focus": "commission",
        "title": "II · Duets",
        "body": "Splitters divide words at a fixed position. Unisons join words in input order. Neither part checks note values. Use one machine for all 2 performances. Each resonator must receive its target word; resonators marked “stay silent” must receive nothing."
      },
      {
        "focus": "board",
        "title": "A nudge",
        "body": "Join the words before appending C so the note is added to the combined word."
      },
      {
        "focus": "board",
        "title": "Search results: spoilers",
        "body": "Minimum: 2 parts. The search found 2 labelled layouts at that size. Required parts: unison, mould. Different layouts can represent the same approach. The reference is one minimum solution."
      }
    ]
  },
  {
    "id": "campaign-duet-swap",
    "title": "Duet II: the swap",
    "chapter": "II · Duets",
    "assignment": "Split each four-note seed in half, then join the second half before the first.",
    "board": {
      "cols": 9,
      "rows": 5
    },
    "fixed": [
      {
        "id": "q1",
        "kind": "quill",
        "x": 1,
        "y": 1
      },
      {
        "id": "r1",
        "kind": "resonator",
        "x": 7,
        "y": 1
      }
    ],
    "palette": {
      "unison": 1,
      "splitter": 1,
      "mould": 1,
      "damper": 1
    },
    "cases": [
      {
        "name": "Aria",
        "seeds": {
          "q1": "ABCD"
        },
        "targets": {
          "r1": "CDAB"
        }
      },
      {
        "name": "Encore",
        "seeds": {
          "q1": "DDBA"
        },
        "targets": {
          "r1": "BADD"
        }
      }
    ],
    "reference": {
      "parts": [
        {
          "id": "p0",
          "kind": "unison",
          "config": {},
          "x": 5,
          "y": 1
        },
        {
          "id": "p1",
          "kind": "splitter",
          "config": {
            "k": 2
          },
          "x": 3,
          "y": 1
        }
      ],
      "wires": [
        {
          "from": {
            "part": "q1",
            "port": "out"
          },
          "to": {
            "part": "p1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "out"
          },
          "to": {
            "part": "r1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "head"
          },
          "to": {
            "part": "p0",
            "port": "tail"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "rest"
          },
          "to": {
            "part": "p0",
            "port": "lead"
          }
        }
      ]
    },
    "meta": {
      "minParts": 2,
      "signaturesAtMin": 1,
      "signaturesCapped": false,
      "forced": [
        "unison",
        "splitter"
      ]
    },
    "walkthrough": [
      {
        "focus": "commission",
        "title": "II · Duets",
        "body": "Splitters divide words at a fixed position. Unisons join words in input order. Neither part checks note values. Use one machine for all 2 performances. Each resonator must receive its target word; resonators marked “stay silent” must receive nothing."
      },
      {
        "focus": "board",
        "title": "A nudge",
        "body": "Set the splitter to 2 and connect its rest output to the unison’s lead input."
      },
      {
        "focus": "board",
        "title": "Search results: spoilers",
        "body": "Minimum: 2 parts. The search found 1 labelled layout at that size. Required parts: unison, splitter. Different layouts can represent the same approach. The reference is one minimum solution."
      }
    ]
  },
  {
    "id": "campaign-duet-insert",
    "title": "Duet III: the graft",
    "chapter": "II · Duets",
    "assignment": "Insert D after the second note of each seed.",
    "board": {
      "cols": 9,
      "rows": 5
    },
    "fixed": [
      {
        "id": "q1",
        "kind": "quill",
        "x": 1,
        "y": 1
      },
      {
        "id": "r1",
        "kind": "resonator",
        "x": 7,
        "y": 1
      }
    ],
    "palette": {
      "unison": 1,
      "splitter": 1,
      "mould": 1,
      "damper": 1
    },
    "cases": [
      {
        "name": "Aria",
        "seeds": {
          "q1": "ABCA"
        },
        "targets": {
          "r1": "ABDCA"
        }
      },
      {
        "name": "Encore",
        "seeds": {
          "q1": "CBAD"
        },
        "targets": {
          "r1": "CBDAD"
        }
      }
    ],
    "reference": {
      "parts": [
        {
          "id": "p0",
          "kind": "unison",
          "config": {},
          "x": 5,
          "y": 1
        },
        {
          "id": "p1",
          "kind": "splitter",
          "config": {
            "k": 2
          },
          "x": 3,
          "y": 1
        },
        {
          "id": "p2",
          "kind": "mould",
          "config": {
            "note": "D"
          },
          "x": 5,
          "y": 3
        }
      ],
      "wires": [
        {
          "from": {
            "part": "q1",
            "port": "out"
          },
          "to": {
            "part": "p1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "out"
          },
          "to": {
            "part": "r1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "head"
          },
          "to": {
            "part": "p2",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "rest"
          },
          "to": {
            "part": "p0",
            "port": "tail"
          }
        },
        {
          "from": {
            "part": "p2",
            "port": "out"
          },
          "to": {
            "part": "p0",
            "port": "lead"
          }
        }
      ]
    },
    "meta": {
      "minParts": 3,
      "signaturesAtMin": 1,
      "signaturesCapped": false,
      "forced": [
        "unison",
        "splitter",
        "mould"
      ]
    },
    "walkthrough": [
      {
        "focus": "commission",
        "title": "II · Duets",
        "body": "Splitters divide words at a fixed position. Unisons join words in input order. Neither part checks note values. Use one machine for all 2 performances. Each resonator must receive its target word; resonators marked “stay silent” must receive nothing."
      },
      {
        "focus": "board",
        "title": "A nudge",
        "body": "Split after the second note, append D to the first half, then join the halves again."
      },
      {
        "focus": "board",
        "title": "Search results: spoilers",
        "body": "Minimum: 3 parts. The search found 1 labelled layout at that size. Required parts: unison, splitter, mould. Different layouts can represent the same approach. The reference is one minimum solution."
      }
    ]
  },
  {
    "id": "campaign-duet-behead",
    "title": "Duet IV: beheaded harmony",
    "chapter": "II · Duets",
    "assignment": "Remove the first note from the second seed, then join it after the first seed.",
    "board": {
      "cols": 9,
      "rows": 5
    },
    "fixed": [
      {
        "id": "q1",
        "kind": "quill",
        "label": "first voice",
        "x": 1,
        "y": 1
      },
      {
        "id": "q2",
        "kind": "quill",
        "label": "second voice",
        "x": 1,
        "y": 3
      },
      {
        "id": "r1",
        "kind": "resonator",
        "x": 5,
        "y": 1
      }
    ],
    "palette": {
      "unison": 1,
      "splitter": 1,
      "mould": 1,
      "damper": 1
    },
    "cases": [
      {
        "name": "Aria",
        "seeds": {
          "q1": "AB",
          "q2": "DCA"
        },
        "targets": {
          "r1": "ABCA"
        }
      },
      {
        "name": "Encore",
        "seeds": {
          "q1": "CA",
          "q2": "BDD"
        },
        "targets": {
          "r1": "CADD"
        }
      }
    ],
    "reference": {
      "parts": [
        {
          "id": "p0",
          "kind": "unison",
          "config": {},
          "x": 3,
          "y": 1
        },
        {
          "id": "p1",
          "kind": "damper",
          "config": {},
          "x": 3,
          "y": 3
        }
      ],
      "wires": [
        {
          "from": {
            "part": "q1",
            "port": "out"
          },
          "to": {
            "part": "p0",
            "port": "lead"
          }
        },
        {
          "from": {
            "part": "q2",
            "port": "out"
          },
          "to": {
            "part": "p1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "out"
          },
          "to": {
            "part": "r1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "out"
          },
          "to": {
            "part": "p0",
            "port": "tail"
          }
        }
      ]
    },
    "meta": {
      "minParts": 2,
      "signaturesAtMin": 1,
      "signaturesCapped": false,
      "forced": [
        "unison",
        "damper"
      ]
    },
    "walkthrough": [
      {
        "focus": "commission",
        "title": "II · Duets",
        "body": "Splitters divide words at a fixed position. Unisons join words in input order. Neither part checks note values. Use one machine for all 2 performances. Each resonator must receive its target word; resonators marked “stay silent” must receive nothing."
      },
      {
        "focus": "board",
        "title": "A nudge",
        "body": "Place the damper on the second input before the unison."
      },
      {
        "focus": "board",
        "title": "Search results: spoilers",
        "body": "Minimum: 2 parts. The search found 1 labelled layout at that size. Required parts: unison, damper. Different layouts can represent the same approach. The reference is one minimum solution."
      }
    ]
  },
  {
    "id": "campaign-reading-stamps",
    "title": "Sight-reading I: two signatures",
    "chapter": "III · Sight-reading",
    "assignment": "Route each word by its first note, then append the note required by its target.",
    "board": {
      "cols": 9,
      "rows": 5
    },
    "fixed": [
      {
        "id": "q1",
        "kind": "quill",
        "x": 1,
        "y": 1
      },
      {
        "id": "r1",
        "kind": "resonator",
        "label": "hall of A",
        "x": 7,
        "y": 1
      },
      {
        "id": "r2",
        "kind": "resonator",
        "label": "hall of B",
        "x": 7,
        "y": 3
      }
    ],
    "palette": {
      "fork": 2,
      "mould": 2
    },
    "cases": [
      {
        "name": "Aria",
        "seeds": {
          "q1": "ACB"
        },
        "targets": {
          "r1": "ACBD"
        }
      },
      {
        "name": "Encore",
        "seeds": {
          "q1": "BCB"
        },
        "targets": {
          "r2": "BCBC"
        }
      }
    ],
    "reference": {
      "parts": [
        {
          "id": "p0",
          "kind": "fork",
          "config": {
            "note": "A",
            "mode": "peek"
          },
          "x": 3,
          "y": 1
        },
        {
          "id": "p1",
          "kind": "mould",
          "config": {
            "note": "C"
          },
          "x": 5,
          "y": 1
        },
        {
          "id": "p2",
          "kind": "mould",
          "config": {
            "note": "D"
          },
          "x": 5,
          "y": 3
        }
      ],
      "wires": [
        {
          "from": {
            "part": "q1",
            "port": "out"
          },
          "to": {
            "part": "p0",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "left"
          },
          "to": {
            "part": "p2",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "right"
          },
          "to": {
            "part": "p1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "out"
          },
          "to": {
            "part": "r2",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p2",
            "port": "out"
          },
          "to": {
            "part": "r1",
            "port": "in"
          }
        }
      ]
    },
    "meta": {
      "minParts": 3,
      "signaturesAtMin": 2,
      "signaturesCapped": false,
      "forced": [
        "fork",
        "mould"
      ]
    },
    "walkthrough": [
      {
        "focus": "commission",
        "title": "III · Sight-reading",
        "body": "Forks route words according to their first note. Different performances can therefore use different paths. Use one machine for all 2 performances. Each resonator must receive its target word; resonators marked “stay silent” must receive nothing."
      },
      {
        "focus": "board",
        "title": "A nudge",
        "body": "Route the word first, then place the correct mould on each output path."
      },
      {
        "focus": "board",
        "title": "Search results: spoilers",
        "body": "Minimum: 3 parts. The search found 2 labelled layouts at that size. Required parts: fork, mould. Different layouts can represent the same approach. The reference is one minimum solution."
      }
    ]
  },
  {
    "id": "campaign-reading-threeway",
    "title": "Sight-reading II: three halls",
    "chapter": "III · Sight-reading",
    "assignment": "Route words beginning with A, B, and C to their matching resonators.",
    "board": {
      "cols": 9,
      "rows": 7
    },
    "fixed": [
      {
        "id": "q1",
        "kind": "quill",
        "x": 1,
        "y": 1
      },
      {
        "id": "r1",
        "kind": "resonator",
        "label": "hall of A",
        "x": 7,
        "y": 1
      },
      {
        "id": "r2",
        "kind": "resonator",
        "label": "hall of B",
        "x": 7,
        "y": 3
      },
      {
        "id": "r3",
        "kind": "resonator",
        "label": "hall of C",
        "x": 7,
        "y": 5
      }
    ],
    "palette": {
      "fork": 2,
      "mould": 2
    },
    "cases": [
      {
        "name": "Aria",
        "seeds": {
          "q1": "AD"
        },
        "targets": {
          "r1": "AD"
        }
      },
      {
        "name": "Encore",
        "seeds": {
          "q1": "BD"
        },
        "targets": {
          "r2": "BD"
        }
      },
      {
        "name": "Coda",
        "seeds": {
          "q1": "CD"
        },
        "targets": {
          "r3": "CD"
        }
      }
    ],
    "reference": {
      "parts": [
        {
          "id": "p0",
          "kind": "fork",
          "config": {
            "note": "A",
            "mode": "peek"
          },
          "x": 3,
          "y": 1
        },
        {
          "id": "p1",
          "kind": "fork",
          "config": {
            "note": "B",
            "mode": "peek"
          },
          "x": 5,
          "y": 1
        }
      ],
      "wires": [
        {
          "from": {
            "part": "q1",
            "port": "out"
          },
          "to": {
            "part": "p0",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "left"
          },
          "to": {
            "part": "r1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "right"
          },
          "to": {
            "part": "p1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "left"
          },
          "to": {
            "part": "r2",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "right"
          },
          "to": {
            "part": "r3",
            "port": "in"
          }
        }
      ]
    },
    "meta": {
      "minParts": 2,
      "signaturesAtMin": 6,
      "signaturesCapped": false,
      "forced": [
        "fork"
      ]
    },
    "walkthrough": [
      {
        "focus": "commission",
        "title": "III · Sight-reading",
        "body": "Forks route words according to their first note. Different performances can therefore use different paths. Use one machine for all 3 performances. Each resonator must receive its target word; resonators marked “stay silent” must receive nothing."
      },
      {
        "focus": "board",
        "title": "A nudge",
        "body": "Use one fork for A. Send its right output to a second fork that checks for B."
      },
      {
        "focus": "board",
        "title": "Search results: spoilers",
        "body": "Minimum: 2 parts. The search found 6 labelled layouts at that size. Required parts: fork. Different layouts can represent the same approach. The reference is one minimum solution."
      }
    ]
  },
  {
    "id": "campaign-wolf-strip-stamp",
    "title": "Wolf I: bitten clean, then signed",
    "chapter": "IV · Wolf notes",
    "assignment": "Remove every leading A, then append C.",
    "board": {
      "cols": 9,
      "rows": 5
    },
    "fixed": [
      {
        "id": "q1",
        "kind": "quill",
        "x": 1,
        "y": 1
      },
      {
        "id": "r1",
        "kind": "resonator",
        "x": 7,
        "y": 1
      }
    ],
    "palette": {
      "fork": 2,
      "mould": 1,
      "damper": 1
    },
    "cases": [
      {
        "name": "Aria",
        "seeds": {
          "q1": "AAB"
        },
        "targets": {
          "r1": "BC"
        }
      },
      {
        "name": "Encore",
        "seeds": {
          "q1": "AB"
        },
        "targets": {
          "r1": "BC"
        }
      },
      {
        "name": "Coda",
        "seeds": {
          "q1": "B"
        },
        "targets": {
          "r1": "BC"
        }
      }
    ],
    "reference": {
      "parts": [
        {
          "id": "p0",
          "kind": "fork",
          "config": {
            "note": "A",
            "mode": "consume"
          },
          "x": 3,
          "y": 1
        },
        {
          "id": "p1",
          "kind": "mould",
          "config": {
            "note": "C"
          },
          "x": 5,
          "y": 1
        }
      ],
      "wires": [
        {
          "from": {
            "part": "q1",
            "port": "out"
          },
          "to": {
            "part": "p0",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "left"
          },
          "to": {
            "part": "p0",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "right"
          },
          "to": {
            "part": "p1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "out"
          },
          "to": {
            "part": "r1",
            "port": "in"
          }
        }
      ]
    },
    "meta": {
      "minParts": 2,
      "signaturesAtMin": 2,
      "signaturesCapped": false,
      "forced": [
        "fork",
        "mould"
      ]
    },
    "walkthrough": [
      {
        "focus": "commission",
        "title": "IV · Wolf notes",
        "body": "A fork in bite mode removes one matching first note. A loop can repeat this until the first note changes. Use one machine for all 3 performances. Each resonator must receive its target word; resonators marked “stay silent” must receive nothing."
      },
      {
        "focus": "board",
        "title": "A nudge",
        "body": "Loop the fork’s matching output back to its input so it can remove more than one A."
      },
      {
        "focus": "board",
        "title": "Search results: spoilers",
        "body": "Minimum: 2 parts. The search found 2 labelled layouts at that size. Required parts: fork, mould. Different layouts can represent the same approach. The reference is one minimum solution."
      }
    ]
  },
  {
    "id": "campaign-wolf-rotate",
    "title": "Wolf II: the rotation",
    "chapter": "IV · Wolf notes",
    "assignment": "Move every leading A to the end of the word.",
    "board": {
      "cols": 9,
      "rows": 5
    },
    "fixed": [
      {
        "id": "q1",
        "kind": "quill",
        "x": 1,
        "y": 1
      },
      {
        "id": "r1",
        "kind": "resonator",
        "x": 7,
        "y": 1
      }
    ],
    "palette": {
      "fork": 2,
      "mould": 1,
      "damper": 1
    },
    "cases": [
      {
        "name": "Aria",
        "seeds": {
          "q1": "AAB"
        },
        "targets": {
          "r1": "BAA"
        }
      },
      {
        "name": "Encore",
        "seeds": {
          "q1": "AB"
        },
        "targets": {
          "r1": "BA"
        }
      },
      {
        "name": "Coda",
        "seeds": {
          "q1": "BB"
        },
        "targets": {
          "r1": "BB"
        }
      }
    ],
    "reference": {
      "parts": [
        {
          "id": "p0",
          "kind": "fork",
          "config": {
            "note": "A",
            "mode": "consume"
          },
          "x": 3,
          "y": 1
        },
        {
          "id": "p1",
          "kind": "mould",
          "config": {
            "note": "A"
          },
          "x": 5,
          "y": 1
        }
      ],
      "wires": [
        {
          "from": {
            "part": "q1",
            "port": "out"
          },
          "to": {
            "part": "p0",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "left"
          },
          "to": {
            "part": "p1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "right"
          },
          "to": {
            "part": "r1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "out"
          },
          "to": {
            "part": "p0",
            "port": "in"
          }
        }
      ]
    },
    "meta": {
      "minParts": 2,
      "signaturesAtMin": 1,
      "signaturesCapped": false,
      "forced": [
        "fork",
        "mould"
      ]
    },
    "walkthrough": [
      {
        "focus": "commission",
        "title": "IV · Wolf notes",
        "body": "A fork in bite mode removes one matching first note. A loop can repeat this until the first note changes. Use one machine for all 3 performances. Each resonator must receive its target word; resonators marked “stay silent” must receive nothing."
      },
      {
        "focus": "board",
        "title": "A nudge",
        "body": "After the fork removes an A, use a mould to append it before returning the word to the fork."
      },
      {
        "focus": "board",
        "title": "Search results: spoilers",
        "body": "Minimum: 2 parts. The search found 1 labelled layout at that size. Required parts: fork, mould. Different layouts can represent the same approach. The reference is one minimum solution."
      }
    ]
  },
  {
    "id": "campaign-wolf-two-teeth",
    "title": "Wolf III: two teeth",
    "chapter": "IV · Wolf notes",
    "assignment": "Remove all leading A notes, then remove all leading B notes.",
    "board": {
      "cols": 9,
      "rows": 5
    },
    "fixed": [
      {
        "id": "q1",
        "kind": "quill",
        "x": 1,
        "y": 1
      },
      {
        "id": "r1",
        "kind": "resonator",
        "x": 7,
        "y": 1
      }
    ],
    "palette": {
      "fork": 2,
      "mould": 1,
      "damper": 1
    },
    "cases": [
      {
        "name": "Aria",
        "seeds": {
          "q1": "AABC"
        },
        "targets": {
          "r1": "C"
        }
      },
      {
        "name": "Encore",
        "seeds": {
          "q1": "ABBC"
        },
        "targets": {
          "r1": "C"
        }
      },
      {
        "name": "Coda",
        "seeds": {
          "q1": "BC"
        },
        "targets": {
          "r1": "C"
        }
      },
      {
        "name": "Reprise",
        "seeds": {
          "q1": "ABAC"
        },
        "targets": {
          "r1": "AC"
        }
      }
    ],
    "reference": {
      "parts": [
        {
          "id": "p0",
          "kind": "fork",
          "config": {
            "note": "A",
            "mode": "consume"
          },
          "x": 3,
          "y": 1
        },
        {
          "id": "p1",
          "kind": "fork",
          "config": {
            "note": "B",
            "mode": "consume"
          },
          "x": 5,
          "y": 1
        }
      ],
      "wires": [
        {
          "from": {
            "part": "q1",
            "port": "out"
          },
          "to": {
            "part": "p0",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "left"
          },
          "to": {
            "part": "p0",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "right"
          },
          "to": {
            "part": "p1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "left"
          },
          "to": {
            "part": "p1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "right"
          },
          "to": {
            "part": "r1",
            "port": "in"
          }
        }
      ]
    },
    "meta": {
      "minParts": 2,
      "signaturesAtMin": 1,
      "signaturesCapped": false,
      "forced": [
        "fork"
      ]
    },
    "walkthrough": [
      {
        "focus": "commission",
        "title": "IV · Wolf notes",
        "body": "A fork in bite mode removes one matching first note. A loop can repeat this until the first note changes. Use one machine for all 4 performances. Each resonator must receive its target word; resonators marked “stay silent” must receive nothing."
      },
      {
        "focus": "board",
        "title": "A nudge",
        "body": "Use one bite loop for A, then send its non-matching output to a second bite loop for B. Check Reprise as well."
      },
      {
        "focus": "board",
        "title": "Search results: spoilers",
        "body": "Minimum: 2 parts. The search found 1 labelled layout at that size. Required parts: fork. Different layouts can represent the same approach. The reference is one minimum solution."
      }
    ]
  },
  {
    "id": "campaign-tangle-stamped-gate",
    "title": "Entanglement I: the stamped gate",
    "chapter": "V · Entanglements",
    "assignment": "Use the label to route the payload. Append D only to payloads sent to the hall of A. Send the label to the spent-labels resonator.",
    "board": {
      "cols": 9,
      "rows": 7
    },
    "fixed": [
      {
        "id": "q1",
        "kind": "quill",
        "label": "the label",
        "x": 1,
        "y": 1
      },
      {
        "id": "q2",
        "kind": "quill",
        "label": "the payload",
        "x": 1,
        "y": 3
      },
      {
        "id": "r1",
        "kind": "resonator",
        "label": "spent labels",
        "x": 7,
        "y": 1
      },
      {
        "id": "r2",
        "kind": "resonator",
        "label": "hall of A",
        "x": 7,
        "y": 3
      },
      {
        "id": "r3",
        "kind": "resonator",
        "label": "hall of B",
        "x": 7,
        "y": 5
      }
    ],
    "palette": {
      "coupling": 1,
      "mould": 1,
      "damper": 1
    },
    "cases": [
      {
        "name": "Aria",
        "seeds": {
          "q1": "A",
          "q2": "CD"
        },
        "targets": {
          "r1": "A",
          "r2": "CDD"
        }
      },
      {
        "name": "Encore",
        "seeds": {
          "q1": "B",
          "q2": "CD"
        },
        "targets": {
          "r1": "B",
          "r3": "CD"
        }
      }
    ],
    "reference": {
      "parts": [
        {
          "id": "p0",
          "kind": "coupling",
          "config": {
            "noteA": "A",
            "noteB": "A"
          },
          "x": 3,
          "y": 1
        },
        {
          "id": "p1",
          "kind": "mould",
          "config": {
            "note": "D"
          },
          "x": 5,
          "y": 1
        }
      ],
      "wires": [
        {
          "from": {
            "part": "q1",
            "port": "out"
          },
          "to": {
            "part": "p0",
            "port": "inA"
          }
        },
        {
          "from": {
            "part": "q2",
            "port": "out"
          },
          "to": {
            "part": "p0",
            "port": "inB"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "outAR"
          },
          "to": {
            "part": "r1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "outBL"
          },
          "to": {
            "part": "p1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "outBR"
          },
          "to": {
            "part": "r3",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "out"
          },
          "to": {
            "part": "r2",
            "port": "in"
          }
        }
      ]
    },
    "meta": {
      "minParts": 2,
      "signaturesAtMin": 2,
      "signaturesCapped": true,
      "forced": [
        "coupling",
        "mould"
      ]
    },
    "walkthrough": [
      {
        "focus": "commission",
        "title": "V · Entanglements",
        "body": "A coupling waits for two words. Each word’s route is determined by the other word’s first note. Use one machine for all 2 performances. Each resonator must receive its target word; resonators marked “stay silent” must receive nothing."
      },
      {
        "focus": "board",
        "title": "A nudge",
        "body": "Connect the payload and label to opposite coupling inputs. Each input is routed by the first note on the other input."
      },
      {
        "focus": "board",
        "title": "Search results: spoilers",
        "body": "Minimum: 2 parts. The search found at least 2 labelled layouts at that size. Required parts: coupling, mould. Different layouts can represent the same approach. The reference is one minimum solution."
      }
    ]
  },
  {
    "id": "campaign-tangle-mutual",
    "title": "Entanglement II: mutual regard",
    "chapter": "V · Entanglements",
    "assignment": "Route each seed according to the first note of the other seed.",
    "board": {
      "cols": 9,
      "rows": 9
    },
    "fixed": [
      {
        "id": "q1",
        "kind": "quill",
        "label": "first voice",
        "x": 1,
        "y": 1
      },
      {
        "id": "q2",
        "kind": "quill",
        "label": "second voice",
        "x": 1,
        "y": 3
      },
      {
        "id": "r1",
        "kind": "resonator",
        "label": "first hall",
        "x": 5,
        "y": 1
      },
      {
        "id": "r2",
        "kind": "resonator",
        "label": "first annex",
        "x": 5,
        "y": 3
      },
      {
        "id": "r3",
        "kind": "resonator",
        "label": "second hall",
        "x": 5,
        "y": 5
      },
      {
        "id": "r4",
        "kind": "resonator",
        "label": "second annex",
        "x": 5,
        "y": 7
      }
    ],
    "palette": {
      "coupling": 1,
      "mould": 1,
      "damper": 1
    },
    "cases": [
      {
        "name": "Aria",
        "seeds": {
          "q1": "AB",
          "q2": "AD"
        },
        "targets": {
          "r1": "AB",
          "r3": "AD"
        }
      },
      {
        "name": "Encore",
        "seeds": {
          "q1": "BB",
          "q2": "AD"
        },
        "targets": {
          "r1": "BB",
          "r4": "AD"
        }
      },
      {
        "name": "Coda",
        "seeds": {
          "q1": "BD",
          "q2": "CB"
        },
        "targets": {
          "r2": "BD",
          "r4": "CB"
        }
      }
    ],
    "reference": {
      "parts": [
        {
          "id": "p0",
          "kind": "coupling",
          "config": {
            "noteA": "A",
            "noteB": "A"
          },
          "x": 3,
          "y": 1
        }
      ],
      "wires": [
        {
          "from": {
            "part": "q1",
            "port": "out"
          },
          "to": {
            "part": "p0",
            "port": "inA"
          }
        },
        {
          "from": {
            "part": "q2",
            "port": "out"
          },
          "to": {
            "part": "p0",
            "port": "inB"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "outAL"
          },
          "to": {
            "part": "r1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "outAR"
          },
          "to": {
            "part": "r2",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "outBL"
          },
          "to": {
            "part": "r3",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "outBR"
          },
          "to": {
            "part": "r4",
            "port": "in"
          }
        }
      ]
    },
    "meta": {
      "minParts": 1,
      "signaturesAtMin": 8,
      "signaturesCapped": false,
      "forced": [
        "coupling"
      ]
    },
    "walkthrough": [
      {
        "focus": "commission",
        "title": "V · Entanglements",
        "body": "A coupling waits for two words. Each word’s route is determined by the other word’s first note. Use one machine for all 3 performances. Each resonator must receive its target word; resonators marked “stay silent” must receive nothing."
      },
      {
        "focus": "board",
        "title": "A nudge",
        "body": "Set both coupling notes, then trace one performance through all four outputs."
      },
      {
        "focus": "board",
        "title": "Search results: spoilers",
        "body": "Minimum: 1 part. The search found 8 labelled layouts at that size. Required parts: coupling. Different layouts can represent the same approach. The reference is one minimum solution."
      }
    ]
  },
  {
    "id": "campaign-tempo-cross",
    "title": "Tempo II: the crossed duet",
    "chapter": "VI · Tempo",
    "assignment": "Make the two target pairs. Delay one input so the farther words are paired together.",
    "board": {
      "cols": 9,
      "rows": 9
    },
    "fixed": [
      {
        "id": "q1",
        "kind": "quill",
        "label": "B: near",
        "x": 1,
        "y": 1
      },
      {
        "id": "q2",
        "kind": "quill",
        "label": "A: far",
        "x": 1,
        "y": 3
      },
      {
        "id": "q3",
        "kind": "quill",
        "label": "near tail",
        "x": 1,
        "y": 5
      },
      {
        "id": "q4",
        "kind": "quill",
        "label": "far tail",
        "x": 1,
        "y": 7
      },
      {
        "id": "r1",
        "kind": "resonator",
        "label": "hall of A",
        "x": 7,
        "y": 1
      },
      {
        "id": "r2",
        "kind": "resonator",
        "label": "the other hall",
        "x": 7,
        "y": 3
      }
    ],
    "palette": {
      "valve": 1,
      "unison": 1,
      "fork": 1
    },
    "cases": [
      {
        "name": "Aria",
        "seeds": {
          "q1": "B",
          "q2": "A",
          "q3": "C",
          "q4": "D"
        },
        "targets": {
          "r1": "AC",
          "r2": "BD"
        }
      },
      {
        "name": "Encore",
        "seeds": {
          "q1": "B",
          "q2": "A",
          "q3": "D",
          "q4": "C"
        },
        "targets": {
          "r1": "AD",
          "r2": "BC"
        }
      }
    ],
    "reference": {
      "parts": [
        {
          "id": "p0",
          "kind": "valve",
          "config": {
            "delay": 1
          },
          "x": 3,
          "y": 1
        },
        {
          "id": "p1",
          "kind": "unison",
          "config": {},
          "x": 3,
          "y": 3
        },
        {
          "id": "p2",
          "kind": "fork",
          "config": {
            "note": "A",
            "mode": "peek"
          },
          "x": 5,
          "y": 1
        }
      ],
      "wires": [
        {
          "from": {
            "part": "q1",
            "port": "out"
          },
          "to": {
            "part": "p0",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "q2",
            "port": "out"
          },
          "to": {
            "part": "p1",
            "port": "lead"
          }
        },
        {
          "from": {
            "part": "q3",
            "port": "out"
          },
          "to": {
            "part": "p1",
            "port": "tail"
          }
        },
        {
          "from": {
            "part": "q4",
            "port": "out"
          },
          "to": {
            "part": "p1",
            "port": "tail"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "out"
          },
          "to": {
            "part": "p1",
            "port": "lead"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "out"
          },
          "to": {
            "part": "p2",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p2",
            "port": "left"
          },
          "to": {
            "part": "r1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p2",
            "port": "right"
          },
          "to": {
            "part": "r2",
            "port": "in"
          }
        }
      ]
    },
    "meta": {
      "minParts": 3,
      "signaturesAtMin": 6,
      "signaturesCapped": true,
      "forced": [
        "unison",
        "fork"
      ],
      "valveAtLayout": true
    },
    "walkthrough": [
      {
        "focus": "commission",
        "title": "VI · Tempo",
        "body": "Wire length sets travel time. A valve adds a selected delay before passing the word through unchanged. Use one machine for all 2 performances. Each resonator must receive its target word; resonators marked “stay silent” must receive nothing."
      },
      {
        "focus": "board",
        "title": "A nudge",
        "body": "Run without a valve and check the event log. Then delay the one path that arrives too early."
      },
      {
        "focus": "board",
        "title": "Search results: spoilers",
        "body": "Minimum: 3 parts. The search found at least 6 labelled layouts at that size. Required parts: unison, fork. With the search’s fixed placement, every solution used a valve. Longer wires can add the same delay in your layout. Different layouts can represent the same approach. The reference is one minimum solution."
      }
    ]
  },
  {
    "id": "campaign-concerto-envelope",
    "title": "Concerto I: the envelope",
    "chapter": "VII · Concerto",
    "assignment": "Split off the first note. Use it to route the remaining word, then send the first note to the spent-headers resonator.",
    "board": {
      "cols": 9,
      "rows": 7
    },
    "fixed": [
      {
        "id": "q1",
        "kind": "quill",
        "x": 1,
        "y": 1
      },
      {
        "id": "r1",
        "kind": "resonator",
        "label": "spent headers",
        "x": 7,
        "y": 1
      },
      {
        "id": "r2",
        "kind": "resonator",
        "label": "hall of A",
        "x": 7,
        "y": 3
      },
      {
        "id": "r3",
        "kind": "resonator",
        "label": "hall of B",
        "x": 7,
        "y": 5
      }
    ],
    "palette": {
      "splitter": 1,
      "coupling": 1,
      "mould": 1,
      "damper": 1
    },
    "cases": [
      {
        "name": "Aria",
        "seeds": {
          "q1": "ACD"
        },
        "targets": {
          "r1": "A",
          "r2": "CD"
        }
      },
      {
        "name": "Encore",
        "seeds": {
          "q1": "BCD"
        },
        "targets": {
          "r1": "B",
          "r3": "CD"
        }
      },
      {
        "name": "Coda",
        "seeds": {
          "q1": "ADD"
        },
        "targets": {
          "r1": "A",
          "r2": "DD"
        }
      }
    ],
    "reference": {
      "parts": [
        {
          "id": "p0",
          "kind": "splitter",
          "config": {
            "k": 1
          },
          "x": 3,
          "y": 1
        },
        {
          "id": "p1",
          "kind": "coupling",
          "config": {
            "noteA": "A",
            "noteB": "A"
          },
          "x": 5,
          "y": 1
        }
      ],
      "wires": [
        {
          "from": {
            "part": "q1",
            "port": "out"
          },
          "to": {
            "part": "p0",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "head"
          },
          "to": {
            "part": "p1",
            "port": "inA"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "rest"
          },
          "to": {
            "part": "p1",
            "port": "inB"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "outAR"
          },
          "to": {
            "part": "r1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "outBL"
          },
          "to": {
            "part": "r2",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "outBR"
          },
          "to": {
            "part": "r3",
            "port": "in"
          }
        }
      ]
    },
    "meta": {
      "minParts": 2,
      "signaturesAtMin": 8,
      "signaturesCapped": true,
      "forced": [
        "splitter",
        "coupling"
      ]
    },
    "walkthrough": [
      {
        "focus": "commission",
        "title": "VII · Concerto",
        "body": "These levels combine splitting, joining, routing, loops, and cross-routing. Use one machine for all 3 performances. Each resonator must receive its target word; resonators marked “stay silent” must receive nothing."
      },
      {
        "focus": "board",
        "title": "A nudge",
        "body": "Split after one note, then connect the two results to opposite coupling inputs."
      },
      {
        "focus": "board",
        "title": "Search results: spoilers",
        "body": "Minimum: 2 parts. The search found at least 8 labelled layouts at that size. Required parts: splitter, coupling. Different layouts can represent the same approach. The reference is one minimum solution."
      }
    ]
  },
  {
    "id": "campaign-concerto-signed",
    "title": "Concerto II: the signed envelope",
    "chapter": "VII · Concerto",
    "assignment": "Split off the first note and use it to route the remaining word. Append A only on the path to the hall of A.",
    "board": {
      "cols": 11,
      "rows": 7
    },
    "fixed": [
      {
        "id": "q1",
        "kind": "quill",
        "x": 1,
        "y": 1
      },
      {
        "id": "r1",
        "kind": "resonator",
        "label": "spent headers",
        "x": 9,
        "y": 1
      },
      {
        "id": "r2",
        "kind": "resonator",
        "label": "hall of A",
        "x": 9,
        "y": 3
      },
      {
        "id": "r3",
        "kind": "resonator",
        "label": "hall of B",
        "x": 9,
        "y": 5
      }
    ],
    "palette": {
      "splitter": 1,
      "coupling": 1,
      "mould": 1
    },
    "cases": [
      {
        "name": "Aria",
        "seeds": {
          "q1": "ACD"
        },
        "targets": {
          "r1": "A",
          "r2": "CDA"
        }
      },
      {
        "name": "Encore",
        "seeds": {
          "q1": "BCD"
        },
        "targets": {
          "r1": "B",
          "r3": "CD"
        }
      },
      {
        "name": "Coda",
        "seeds": {
          "q1": "ADC"
        },
        "targets": {
          "r1": "A",
          "r2": "DCA"
        }
      }
    ],
    "reference": {
      "parts": [
        {
          "id": "p0",
          "kind": "splitter",
          "config": {
            "k": 1
          },
          "x": 3,
          "y": 1
        },
        {
          "id": "p1",
          "kind": "coupling",
          "config": {
            "noteA": "A",
            "noteB": "A"
          },
          "x": 5,
          "y": 1
        },
        {
          "id": "p2",
          "kind": "mould",
          "config": {
            "note": "A"
          },
          "x": 7,
          "y": 1
        }
      ],
      "wires": [
        {
          "from": {
            "part": "q1",
            "port": "out"
          },
          "to": {
            "part": "p0",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "head"
          },
          "to": {
            "part": "p1",
            "port": "inA"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "rest"
          },
          "to": {
            "part": "p1",
            "port": "inB"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "outAR"
          },
          "to": {
            "part": "r1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "outBL"
          },
          "to": {
            "part": "p2",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "outBR"
          },
          "to": {
            "part": "r3",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p2",
            "port": "out"
          },
          "to": {
            "part": "r2",
            "port": "in"
          }
        }
      ]
    },
    "meta": {
      "minParts": 3,
      "signaturesAtMin": 8,
      "signaturesCapped": true,
      "forced": [
        "splitter",
        "coupling",
        "mould"
      ]
    },
    "walkthrough": [
      {
        "focus": "commission",
        "title": "VII · Concerto",
        "body": "These levels combine splitting, joining, routing, loops, and cross-routing. Use one machine for all 3 performances. Each resonator must receive its target word; resonators marked “stay silent” must receive nothing."
      },
      {
        "focus": "board",
        "title": "A nudge",
        "body": "Route the body first, then place the mould only on the hall-of-A output."
      },
      {
        "focus": "board",
        "title": "Search results: spoilers",
        "body": "Minimum: 3 parts. The search found at least 8 labelled layouts at that size. Required parts: splitter, coupling, mould. Different layouts can represent the same approach. The reference is one minimum solution."
      }
    ]
  },
  {
    "id": "campaign-concerto-wolf",
    "title": "Concerto III: the wolf’s commission",
    "chapter": "VII · Concerto",
    "assignment": "Remove all leading A notes. Route the result by its new first note, then append the note required by that target.",
    "board": {
      "cols": 11,
      "rows": 5
    },
    "fixed": [
      {
        "id": "q1",
        "kind": "quill",
        "x": 1,
        "y": 1
      },
      {
        "id": "r1",
        "kind": "resonator",
        "label": "hall of B",
        "x": 9,
        "y": 1
      },
      {
        "id": "r2",
        "kind": "resonator",
        "label": "hall of C",
        "x": 9,
        "y": 3
      }
    ],
    "palette": {
      "fork": 2,
      "mould": 2
    },
    "cases": [
      {
        "name": "Aria",
        "seeds": {
          "q1": "AABC"
        },
        "targets": {
          "r1": "BCC"
        }
      },
      {
        "name": "Encore",
        "seeds": {
          "q1": "ACB"
        },
        "targets": {
          "r2": "CBB"
        }
      },
      {
        "name": "Coda",
        "seeds": {
          "q1": "BC"
        },
        "targets": {
          "r1": "BCC"
        }
      },
      {
        "name": "Reprise",
        "seeds": {
          "q1": "CB"
        },
        "targets": {
          "r2": "CBB"
        }
      }
    ],
    "reference": {
      "parts": [
        {
          "id": "p0",
          "kind": "fork",
          "config": {
            "note": "A",
            "mode": "consume"
          },
          "x": 3,
          "y": 1
        },
        {
          "id": "p1",
          "kind": "fork",
          "config": {
            "note": "B",
            "mode": "peek"
          },
          "x": 5,
          "y": 1
        },
        {
          "id": "p2",
          "kind": "mould",
          "config": {
            "note": "B"
          },
          "x": 7,
          "y": 1
        },
        {
          "id": "p3",
          "kind": "mould",
          "config": {
            "note": "C"
          },
          "x": 7,
          "y": 3
        }
      ],
      "wires": [
        {
          "from": {
            "part": "q1",
            "port": "out"
          },
          "to": {
            "part": "p0",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "left"
          },
          "to": {
            "part": "p0",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "right"
          },
          "to": {
            "part": "p1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "left"
          },
          "to": {
            "part": "p3",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "right"
          },
          "to": {
            "part": "p2",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p2",
            "port": "out"
          },
          "to": {
            "part": "r2",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p3",
            "port": "out"
          },
          "to": {
            "part": "r1",
            "port": "in"
          }
        }
      ]
    },
    "meta": {
      "minParts": 4,
      "signaturesAtMin": 4,
      "signaturesCapped": false,
      "forced": [
        "fork",
        "mould"
      ]
    },
    "walkthrough": [
      {
        "focus": "commission",
        "title": "VII · Concerto",
        "body": "These levels combine splitting, joining, routing, loops, and cross-routing. Use one machine for all 4 performances. Each resonator must receive its target word; resonators marked “stay silent” must receive nothing."
      },
      {
        "focus": "board",
        "title": "A nudge",
        "body": "Remove A notes in a loop, route the result once, then place the correct mould on each output path."
      },
      {
        "focus": "board",
        "title": "Search results: spoilers",
        "body": "Minimum: 4 parts. The search found 4 labelled layouts at that size. Required parts: fork, mould. Different layouts can represent the same approach. The reference is one minimum solution."
      }
    ]
  },
];
