// GENERATED by search/campaign-search.mjs: regenerate, do not hand-edit.
// Every level below was found by exhaustive machine search: the reference
// build is the smallest solving machine the instrument found, and the
// walkthrough contains only player-facing guidance.

export const CAMPAIGN = [
  {
    "id": "campaign-etude-1",
    "title": "Étude I",
    "chapter": "I · Études",
    "board": {
      "cols": 9,
      "rows": 5
    },
    "fixed": [
      {
        "id": "q1",
        "kind": "quill",
        "x": 1,
        "y": 1
      },
      {
        "id": "r1",
        "kind": "resonator",
        "x": 7,
        "y": 1
      }
    ],
    "palette": {
      "mould": 2,
      "damper": 2
    },
    "cases": [
      {
        "name": "Aria",
        "seeds": {
          "q1": "DAB"
        },
        "targets": {
          "r1": "ABC"
        }
      },
      {
        "name": "Encore",
        "seeds": {
          "q1": "DBA"
        },
        "targets": {
          "r1": "BAC"
        }
      },
      {
        "name": "Coda",
        "seeds": {
          "q1": "DBB"
        },
        "targets": {
          "r1": "BBC"
        }
      }
    ],
    "reference": {
      "parts": [
        {
          "id": "p0",
          "kind": "mould",
          "config": {
            "note": "C"
          },
          "x": 3,
          "y": 1
        },
        {
          "id": "p1",
          "kind": "damper",
          "config": {},
          "x": 5,
          "y": 1
        }
      ],
      "wires": [
        {
          "from": {
            "part": "q1",
            "port": "out"
          },
          "to": {
            "part": "p0",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "out"
          },
          "to": {
            "part": "p1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "out"
          },
          "to": {
            "part": "r1",
            "port": "in"
          }
        }
      ]
    },
    "meta": {
      "minParts": 2,
      "signaturesAtMin": 2,
      "signaturesCapped": false,
      "forced": [
        "mould",
        "damper"
      ]
    },
    "walkthrough": [
      {
        "focus": "commission",
        "title": "I · Études",
        "body": "Moulds add marbles, and dampers remove lead marbles. These parts do not inspect the train. Use one machine for all 3 performances. Each resonator must receive its target train; resonators marked “stay silent” must receive nothing."
      },
      {
        "focus": "board",
        "title": "A nudge",
        "body": "Place one damper and one mould in a line. Test both possible orders."
      }
    ]
  },
  {
    "id": "campaign-etude-3",
    "title": "Étude II",
    "chapter": "I · Études",
    "board": {
      "cols": 9,
      "rows": 5
    },
    "fixed": [
      {
        "id": "q1",
        "kind": "quill",
        "x": 1,
        "y": 1
      },
      {
        "id": "r1",
        "kind": "resonator",
        "x": 7,
        "y": 1
      }
    ],
    "palette": {
      "mould": 2,
      "damper": 2
    },
    "cases": [
      {
        "name": "Aria",
        "seeds": {
          "q1": "A"
        },
        "targets": {
          "r1": "ACD"
        }
      },
      {
        "name": "Encore",
        "seeds": {
          "q1": "BA"
        },
        "targets": {
          "r1": "BACD"
        }
      },
      {
        "name": "Coda",
        "seeds": {
          "q1": "DBA"
        },
        "targets": {
          "r1": "DBACD"
        }
      }
    ],
    "reference": {
      "parts": [
        {
          "id": "p0",
          "kind": "mould",
          "config": {
            "note": "C"
          },
          "x": 3,
          "y": 1
        },
        {
          "id": "p1",
          "kind": "mould",
          "config": {
            "note": "D"
          },
          "x": 5,
          "y": 1
        }
      ],
      "wires": [
        {
          "from": {
            "part": "q1",
            "port": "out"
          },
          "to": {
            "part": "p0",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "out"
          },
          "to": {
            "part": "p1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "out"
          },
          "to": {
            "part": "r1",
            "port": "in"
          }
        }
      ]
    },
    "meta": {
      "minParts": 2,
      "signaturesAtMin": 1,
      "signaturesCapped": false,
      "forced": [
        "mould"
      ]
    },
    "walkthrough": [
      {
        "focus": "commission",
        "title": "I · Études",
        "body": "Moulds add marbles, and dampers remove lead marbles. These parts do not inspect the train. Use one machine for all 3 performances. Each resonator must receive its target train; resonators marked “stay silent” must receive nothing."
      },
      {
        "focus": "board",
        "title": "A nudge",
        "body": "Use two moulds. Their order determines the final two marbles."
      }
    ]
  },
  {
    "id": "campaign-etude-2",
    "title": "Étude III",
    "chapter": "I · Études",
    "board": {
      "cols": 11,
      "rows": 5
    },
    "fixed": [
      {
        "id": "q1",
        "kind": "quill",
        "x": 1,
        "y": 1
      },
      {
        "id": "r1",
        "kind": "resonator",
        "x": 9,
        "y": 1
      }
    ],
    "palette": {
      "mould": 2,
      "damper": 2
    },
    "cases": [
      {
        "name": "Aria",
        "seeds": {
          "q1": "CDAA"
        },
        "targets": {
          "r1": "AAB"
        }
      },
      {
        "name": "Encore",
        "seeds": {
          "q1": "CDDA"
        },
        "targets": {
          "r1": "DAB"
        }
      },
      {
        "name": "Coda",
        "seeds": {
          "q1": "CDAD"
        },
        "targets": {
          "r1": "ADB"
        }
      }
    ],
    "reference": {
      "parts": [
        {
          "id": "p0",
          "kind": "mould",
          "config": {
            "note": "B"
          },
          "x": 3,
          "y": 1
        },
        {
          "id": "p1",
          "kind": "damper",
          "config": {},
          "x": 5,
          "y": 1
        },
        {
          "id": "p2",
          "kind": "damper",
          "config": {},
          "x": 7,
          "y": 1
        }
      ],
      "wires": [
        {
          "from": {
            "part": "q1",
            "port": "out"
          },
          "to": {
            "part": "p0",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "out"
          },
          "to": {
            "part": "p1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "out"
          },
          "to": {
            "part": "p2",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p2",
            "port": "out"
          },
          "to": {
            "part": "r1",
            "port": "in"
          }
        }
      ]
    },
    "meta": {
      "minParts": 3,
      "signaturesAtMin": 3,
      "signaturesCapped": false,
      "forced": [
        "mould",
        "damper"
      ]
    },
    "walkthrough": [
      {
        "focus": "commission",
        "title": "I · Études",
        "body": "Moulds add marbles, and dampers remove lead marbles. These parts do not inspect the train. Use one machine for all 3 performances. Each resonator must receive its target train; resonators marked “stay silent” must receive nothing."
      },
      {
        "focus": "board",
        "title": "A nudge",
        "body": "A damper removes exactly one lead marble per pass. Two stray marbles mean the train must meet a damper twice."
      }
    ]
  },
  {
    "id": "campaign-etude-4",
    "title": "Étude IV",
    "chapter": "I · Études",
    "board": {
      "cols": 11,
      "rows": 5
    },
    "fixed": [
      {
        "id": "q1",
        "kind": "quill",
        "x": 1,
        "y": 1
      },
      {
        "id": "r1",
        "kind": "resonator",
        "x": 9,
        "y": 1
      }
    ],
    "palette": {
      "mould": 2,
      "damper": 2
    },
    "cases": [
      {
        "name": "Aria",
        "seeds": {
          "q1": "BAB"
        },
        "targets": {
          "r1": "ABDC"
        }
      },
      {
        "name": "Encore",
        "seeds": {
          "q1": "BBA"
        },
        "targets": {
          "r1": "BADC"
        }
      },
      {
        "name": "Coda",
        "seeds": {
          "q1": "BBB"
        },
        "targets": {
          "r1": "BBDC"
        }
      }
    ],
    "reference": {
      "parts": [
        {
          "id": "p0",
          "kind": "mould",
          "config": {
            "note": "C"
          },
          "x": 5,
          "y": 1
        },
        {
          "id": "p1",
          "kind": "mould",
          "config": {
            "note": "D"
          },
          "x": 3,
          "y": 1
        },
        {
          "id": "p2",
          "kind": "damper",
          "config": {},
          "x": 7,
          "y": 1
        }
      ],
      "wires": [
        {
          "from": {
            "part": "q1",
            "port": "out"
          },
          "to": {
            "part": "p1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "out"
          },
          "to": {
            "part": "p2",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "out"
          },
          "to": {
            "part": "p0",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p2",
            "port": "out"
          },
          "to": {
            "part": "r1",
            "port": "in"
          }
        }
      ]
    },
    "meta": {
      "minParts": 3,
      "signaturesAtMin": 3,
      "signaturesCapped": false,
      "forced": [
        "mould",
        "damper"
      ]
    },
    "walkthrough": [
      {
        "focus": "commission",
        "title": "I · Études",
        "body": "Moulds add marbles, and dampers remove lead marbles. These parts do not inspect the train. Use one machine for all 3 performances. Each resonator must receive its target train; resonators marked “stay silent” must receive nothing."
      },
      {
        "focus": "board",
        "title": "A nudge",
        "body": "Place one damper followed by two moulds. Put the C mould last because the target ends in C."
      }
    ]
  },
  {
    "id": "campaign-duet-merge-stamp",
    "title": "Duet I: merge and stamp",
    "chapter": "II · Duets",
    "board": {
      "cols": 9,
      "rows": 5
    },
    "fixed": [
      {
        "id": "q1",
        "kind": "quill",
        "label": "first voice",
        "x": 1,
        "y": 1
      },
      {
        "id": "q2",
        "kind": "quill",
        "label": "second voice",
        "x": 1,
        "y": 3
      },
      {
        "id": "r1",
        "kind": "resonator",
        "x": 7,
        "y": 1
      }
    ],
    "palette": {
      "unison": 1,
      "splitter": 1,
      "mould": 1,
      "damper": 1
    },
    "cases": [
      {
        "name": "Aria",
        "seeds": {
          "q1": "AB",
          "q2": "DA"
        },
        "targets": {
          "r1": "ABDAC"
        }
      },
      {
        "name": "Encore",
        "seeds": {
          "q1": "BD",
          "q2": "AB"
        },
        "targets": {
          "r1": "BDABC"
        }
      }
    ],
    "reference": {
      "parts": [
        {
          "id": "p0",
          "kind": "unison",
          "config": {},
          "x": 3,
          "y": 1
        },
        {
          "id": "p1",
          "kind": "mould",
          "config": {
            "note": "C"
          },
          "x": 5,
          "y": 1
        }
      ],
      "wires": [
        {
          "from": {
            "part": "q1",
            "port": "out"
          },
          "to": {
            "part": "p0",
            "port": "lead"
          }
        },
        {
          "from": {
            "part": "q2",
            "port": "out"
          },
          "to": {
            "part": "p0",
            "port": "tail"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "out"
          },
          "to": {
            "part": "p1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "out"
          },
          "to": {
            "part": "r1",
            "port": "in"
          }
        }
      ]
    },
    "meta": {
      "minParts": 2,
      "signaturesAtMin": 2,
      "signaturesCapped": false,
      "forced": [
        "unison",
        "mould"
      ]
    },
    "walkthrough": [
      {
        "focus": "commission",
        "title": "II · Duets",
        "body": "Splitters divide marble trains at a fixed position. Unisons join trains in input order. Neither part checks the letters on the marbles. Use one machine for all 2 performances. Each resonator must receive its target train; resonators marked “stay silent” must receive nothing."
      },
      {
        "focus": "board",
        "title": "A nudge",
        "body": "Join the trains before adding C so the marble is added to the combined train."
      }
    ]
  },
  {
    "id": "campaign-duet-swap",
    "title": "Duet II: the swap",
    "chapter": "II · Duets",
    "board": {
      "cols": 9,
      "rows": 5
    },
    "fixed": [
      {
        "id": "q1",
        "kind": "quill",
        "x": 1,
        "y": 1
      },
      {
        "id": "r1",
        "kind": "resonator",
        "x": 7,
        "y": 1
      }
    ],
    "palette": {
      "unison": 1,
      "splitter": 1,
      "mould": 1,
      "damper": 1
    },
    "cases": [
      {
        "name": "Aria",
        "seeds": {
          "q1": "ABCD"
        },
        "targets": {
          "r1": "CDAB"
        }
      },
      {
        "name": "Encore",
        "seeds": {
          "q1": "DDBA"
        },
        "targets": {
          "r1": "BADD"
        }
      }
    ],
    "reference": {
      "parts": [
        {
          "id": "p0",
          "kind": "unison",
          "config": {},
          "x": 5,
          "y": 1
        },
        {
          "id": "p1",
          "kind": "splitter",
          "config": {
            "k": 2
          },
          "x": 3,
          "y": 1
        }
      ],
      "wires": [
        {
          "from": {
            "part": "q1",
            "port": "out"
          },
          "to": {
            "part": "p1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "out"
          },
          "to": {
            "part": "r1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "head"
          },
          "to": {
            "part": "p0",
            "port": "tail"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "rest"
          },
          "to": {
            "part": "p0",
            "port": "lead"
          }
        }
      ]
    },
    "meta": {
      "minParts": 2,
      "signaturesAtMin": 1,
      "signaturesCapped": false,
      "forced": [
        "unison",
        "splitter"
      ]
    },
    "walkthrough": [
      {
        "focus": "commission",
        "title": "II · Duets",
        "body": "Splitters divide marble trains at a fixed position. Unisons join trains in input order. Neither part checks the letters on the marbles. Use one machine for all 2 performances. Each resonator must receive its target train; resonators marked “stay silent” must receive nothing."
      },
      {
        "focus": "board",
        "title": "A nudge",
        "body": "Set the splitter to 2 and connect its rest output to the unison’s lead input."
      }
    ]
  },
  {
    "id": "campaign-duet-insert",
    "title": "Duet III: the graft",
    "chapter": "II · Duets",
    "board": {
      "cols": 9,
      "rows": 5
    },
    "fixed": [
      {
        "id": "q1",
        "kind": "quill",
        "x": 1,
        "y": 1
      },
      {
        "id": "r1",
        "kind": "resonator",
        "x": 7,
        "y": 1
      }
    ],
    "palette": {
      "unison": 1,
      "splitter": 1,
      "mould": 1,
      "damper": 1
    },
    "cases": [
      {
        "name": "Aria",
        "seeds": {
          "q1": "ABCA"
        },
        "targets": {
          "r1": "ABDCA"
        }
      },
      {
        "name": "Encore",
        "seeds": {
          "q1": "CBAD"
        },
        "targets": {
          "r1": "CBDAD"
        }
      }
    ],
    "reference": {
      "parts": [
        {
          "id": "p0",
          "kind": "unison",
          "config": {},
          "x": 5,
          "y": 1
        },
        {
          "id": "p1",
          "kind": "splitter",
          "config": {
            "k": 2
          },
          "x": 3,
          "y": 1
        },
        {
          "id": "p2",
          "kind": "mould",
          "config": {
            "note": "D"
          },
          "x": 5,
          "y": 3
        }
      ],
      "wires": [
        {
          "from": {
            "part": "q1",
            "port": "out"
          },
          "to": {
            "part": "p1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "out"
          },
          "to": {
            "part": "r1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "head"
          },
          "to": {
            "part": "p2",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "rest"
          },
          "to": {
            "part": "p0",
            "port": "tail"
          }
        },
        {
          "from": {
            "part": "p2",
            "port": "out"
          },
          "to": {
            "part": "p0",
            "port": "lead"
          }
        }
      ]
    },
    "meta": {
      "minParts": 3,
      "signaturesAtMin": 1,
      "signaturesCapped": false,
      "forced": [
        "unison",
        "splitter",
        "mould"
      ]
    },
    "walkthrough": [
      {
        "focus": "commission",
        "title": "II · Duets",
        "body": "Splitters divide marble trains at a fixed position. Unisons join trains in input order. Neither part checks the letters on the marbles. Use one machine for all 2 performances. Each resonator must receive its target train; resonators marked “stay silent” must receive nothing."
      },
      {
        "focus": "board",
        "title": "A nudge",
        "body": "Split after the second marble, add D to the first half, then join the halves again."
      }
    ]
  },
  {
    "id": "campaign-duet-behead",
    "title": "Duet IV: beheaded harmony",
    "chapter": "II · Duets",
    "board": {
      "cols": 9,
      "rows": 5
    },
    "fixed": [
      {
        "id": "q1",
        "kind": "quill",
        "label": "first voice",
        "x": 1,
        "y": 1
      },
      {
        "id": "q2",
        "kind": "quill",
        "label": "second voice",
        "x": 1,
        "y": 3
      },
      {
        "id": "r1",
        "kind": "resonator",
        "x": 5,
        "y": 1
      }
    ],
    "palette": {
      "unison": 1,
      "splitter": 1,
      "mould": 1,
      "damper": 1
    },
    "cases": [
      {
        "name": "Aria",
        "seeds": {
          "q1": "AB",
          "q2": "DCA"
        },
        "targets": {
          "r1": "ABCA"
        }
      },
      {
        "name": "Encore",
        "seeds": {
          "q1": "CA",
          "q2": "BDD"
        },
        "targets": {
          "r1": "CADD"
        }
      }
    ],
    "reference": {
      "parts": [
        {
          "id": "p0",
          "kind": "unison",
          "config": {},
          "x": 3,
          "y": 1
        },
        {
          "id": "p1",
          "kind": "damper",
          "config": {},
          "x": 3,
          "y": 3
        }
      ],
      "wires": [
        {
          "from": {
            "part": "q1",
            "port": "out"
          },
          "to": {
            "part": "p0",
            "port": "lead"
          }
        },
        {
          "from": {
            "part": "q2",
            "port": "out"
          },
          "to": {
            "part": "p1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "out"
          },
          "to": {
            "part": "r1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "out"
          },
          "to": {
            "part": "p0",
            "port": "tail"
          }
        }
      ]
    },
    "meta": {
      "minParts": 2,
      "signaturesAtMin": 1,
      "signaturesCapped": false,
      "forced": [
        "unison",
        "damper"
      ]
    },
    "walkthrough": [
      {
        "focus": "commission",
        "title": "II · Duets",
        "body": "Splitters divide marble trains at a fixed position. Unisons join trains in input order. Neither part checks the letters on the marbles. Use one machine for all 2 performances. Each resonator must receive its target train; resonators marked “stay silent” must receive nothing."
      },
      {
        "focus": "board",
        "title": "A nudge",
        "body": "Place the damper on the second input before the unison."
      }
    ]
  },
  {
    "id": "campaign-reading-stamps",
    "title": "Sight-reading I: two signatures",
    "chapter": "III · Sight-reading",
    "board": {
      "cols": 9,
      "rows": 5
    },
    "fixed": [
      {
        "id": "q1",
        "kind": "quill",
        "x": 1,
        "y": 1
      },
      {
        "id": "r1",
        "kind": "resonator",
        "label": "hall of A",
        "x": 7,
        "y": 1
      },
      {
        "id": "r2",
        "kind": "resonator",
        "label": "hall of B",
        "x": 7,
        "y": 3
      }
    ],
    "palette": {
      "fork": 2,
      "mould": 2
    },
    "cases": [
      {
        "name": "Aria",
        "seeds": {
          "q1": "ACB"
        },
        "targets": {
          "r1": "ACBD"
        }
      },
      {
        "name": "Encore",
        "seeds": {
          "q1": "BCB"
        },
        "targets": {
          "r2": "BCBC"
        }
      }
    ],
    "reference": {
      "parts": [
        {
          "id": "p0",
          "kind": "fork",
          "config": {
            "note": "A",
            "mode": "peek"
          },
          "x": 3,
          "y": 1
        },
        {
          "id": "p1",
          "kind": "mould",
          "config": {
            "note": "C"
          },
          "x": 5,
          "y": 1
        },
        {
          "id": "p2",
          "kind": "mould",
          "config": {
            "note": "D"
          },
          "x": 5,
          "y": 3
        }
      ],
      "wires": [
        {
          "from": {
            "part": "q1",
            "port": "out"
          },
          "to": {
            "part": "p0",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "left"
          },
          "to": {
            "part": "p2",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "right"
          },
          "to": {
            "part": "p1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "out"
          },
          "to": {
            "part": "r2",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p2",
            "port": "out"
          },
          "to": {
            "part": "r1",
            "port": "in"
          }
        }
      ]
    },
    "meta": {
      "minParts": 3,
      "signaturesAtMin": 2,
      "signaturesCapped": false,
      "forced": [
        "fork",
        "mould"
      ]
    },
    "walkthrough": [
      {
        "focus": "commission",
        "title": "III · Sight-reading",
        "body": "Tuning Forks route trains according to their lead marble. Different performances can therefore use different paths. Use one machine for all 2 performances. Each resonator must receive its target train; resonators marked “stay silent” must receive nothing."
      },
      {
        "focus": "board",
        "title": "A nudge",
        "body": "Route the train first, then place the correct mould on each output path."
      }
    ]
  },
  {
    "id": "campaign-reading-threeway",
    "title": "Sight-reading II: three halls",
    "chapter": "III · Sight-reading",
    "board": {
      "cols": 9,
      "rows": 7
    },
    "fixed": [
      {
        "id": "q1",
        "kind": "quill",
        "x": 1,
        "y": 1
      },
      {
        "id": "r1",
        "kind": "resonator",
        "label": "hall of A",
        "x": 7,
        "y": 1
      },
      {
        "id": "r2",
        "kind": "resonator",
        "label": "hall of B",
        "x": 7,
        "y": 3
      },
      {
        "id": "r3",
        "kind": "resonator",
        "label": "hall of C",
        "x": 7,
        "y": 5
      }
    ],
    "palette": {
      "fork": 2,
      "mould": 2
    },
    "cases": [
      {
        "name": "Aria",
        "seeds": {
          "q1": "AD"
        },
        "targets": {
          "r1": "AD"
        }
      },
      {
        "name": "Encore",
        "seeds": {
          "q1": "BD"
        },
        "targets": {
          "r2": "BD"
        }
      },
      {
        "name": "Coda",
        "seeds": {
          "q1": "CD"
        },
        "targets": {
          "r3": "CD"
        }
      }
    ],
    "reference": {
      "parts": [
        {
          "id": "p0",
          "kind": "fork",
          "config": {
            "note": "A",
            "mode": "peek"
          },
          "x": 3,
          "y": 1
        },
        {
          "id": "p1",
          "kind": "fork",
          "config": {
            "note": "B",
            "mode": "peek"
          },
          "x": 5,
          "y": 1
        }
      ],
      "wires": [
        {
          "from": {
            "part": "q1",
            "port": "out"
          },
          "to": {
            "part": "p0",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "left"
          },
          "to": {
            "part": "r1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "right"
          },
          "to": {
            "part": "p1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "left"
          },
          "to": {
            "part": "r2",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "right"
          },
          "to": {
            "part": "r3",
            "port": "in"
          }
        }
      ]
    },
    "meta": {
      "minParts": 2,
      "signaturesAtMin": 6,
      "signaturesCapped": false,
      "forced": [
        "fork"
      ]
    },
    "walkthrough": [
      {
        "focus": "commission",
        "title": "III · Sight-reading",
        "body": "Tuning Forks route trains according to their lead marble. Different performances can therefore use different paths. Use one machine for all 3 performances. Each resonator must receive its target train; resonators marked “stay silent” must receive nothing."
      },
      {
        "focus": "board",
        "title": "A nudge",
        "body": "Use one fork for A. Send other (≠) to a second fork that checks for B."
      }
    ]
  },
  {
    "id": "campaign-wolf-strip-stamp",
    "title": "Wolf I: bitten clean, then signed",
    "chapter": "IV · Wolf notes",
    "board": {
      "cols": 9,
      "rows": 5
    },
    "fixed": [
      {
        "id": "q1",
        "kind": "quill",
        "x": 1,
        "y": 1
      },
      {
        "id": "r1",
        "kind": "resonator",
        "x": 7,
        "y": 1
      }
    ],
    "palette": {
      "fork": 2,
      "mould": 1,
      "damper": 1
    },
    "cases": [
      {
        "name": "Aria",
        "seeds": {
          "q1": "AAB"
        },
        "targets": {
          "r1": "BC"
        }
      },
      {
        "name": "Encore",
        "seeds": {
          "q1": "AB"
        },
        "targets": {
          "r1": "BC"
        }
      },
      {
        "name": "Coda",
        "seeds": {
          "q1": "B"
        },
        "targets": {
          "r1": "BC"
        }
      }
    ],
    "reference": {
      "parts": [
        {
          "id": "p0",
          "kind": "fork",
          "config": {
            "note": "A",
            "mode": "consume"
          },
          "x": 3,
          "y": 1
        },
        {
          "id": "p1",
          "kind": "mould",
          "config": {
            "note": "C"
          },
          "x": 5,
          "y": 1
        }
      ],
      "wires": [
        {
          "from": {
            "part": "q1",
            "port": "out"
          },
          "to": {
            "part": "p0",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "left"
          },
          "to": {
            "part": "p0",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "right"
          },
          "to": {
            "part": "p1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "out"
          },
          "to": {
            "part": "r1",
            "port": "in"
          }
        }
      ]
    },
    "meta": {
      "minParts": 2,
      "signaturesAtMin": 2,
      "signaturesCapped": false,
      "forced": [
        "fork",
        "mould"
      ]
    },
    "walkthrough": [
      {
        "focus": "commission",
        "title": "IV · Wolf notes",
        "body": "A Tuning Fork in bite mode removes one matching lead marble. A loop can repeat this until the lead marble changes. Use one machine for all 3 performances. Each resonator must receive its target train; resonators marked “stay silent” must receive nothing."
      },
      {
        "focus": "board",
        "title": "A nudge",
        "body": "Loop the fork’s matching output back to its input so it can remove more than one A."
      }
    ]
  },
  {
    "id": "campaign-wolf-rotate",
    "title": "Wolf II: the rotation",
    "chapter": "IV · Wolf notes",
    "board": {
      "cols": 9,
      "rows": 5
    },
    "fixed": [
      {
        "id": "q1",
        "kind": "quill",
        "x": 1,
        "y": 1
      },
      {
        "id": "r1",
        "kind": "resonator",
        "x": 7,
        "y": 1
      }
    ],
    "palette": {
      "fork": 2,
      "mould": 1,
      "damper": 1
    },
    "cases": [
      {
        "name": "Aria",
        "seeds": {
          "q1": "AAB"
        },
        "targets": {
          "r1": "BAA"
        }
      },
      {
        "name": "Encore",
        "seeds": {
          "q1": "AB"
        },
        "targets": {
          "r1": "BA"
        }
      },
      {
        "name": "Coda",
        "seeds": {
          "q1": "BB"
        },
        "targets": {
          "r1": "BB"
        }
      }
    ],
    "reference": {
      "parts": [
        {
          "id": "p0",
          "kind": "fork",
          "config": {
            "note": "A",
            "mode": "consume"
          },
          "x": 3,
          "y": 1
        },
        {
          "id": "p1",
          "kind": "mould",
          "config": {
            "note": "A"
          },
          "x": 5,
          "y": 1
        }
      ],
      "wires": [
        {
          "from": {
            "part": "q1",
            "port": "out"
          },
          "to": {
            "part": "p0",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "left"
          },
          "to": {
            "part": "p1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "right"
          },
          "to": {
            "part": "r1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "out"
          },
          "to": {
            "part": "p0",
            "port": "in"
          }
        }
      ]
    },
    "meta": {
      "minParts": 2,
      "signaturesAtMin": 1,
      "signaturesCapped": false,
      "forced": [
        "fork",
        "mould"
      ]
    },
    "walkthrough": [
      {
        "focus": "commission",
        "title": "IV · Wolf notes",
        "body": "A Tuning Fork in bite mode removes one matching lead marble. A loop can repeat this until the lead marble changes. Use one machine for all 3 performances. Each resonator must receive its target train; resonators marked “stay silent” must receive nothing."
      },
      {
        "focus": "board",
        "title": "A nudge",
        "body": "After the Tuning Fork removes an A marble, use a Mould to add it to the tail before returning the train."
      }
    ]
  },
  {
    "id": "campaign-wolf-two-teeth",
    "title": "Wolf III: two teeth",
    "chapter": "IV · Wolf notes",
    "board": {
      "cols": 9,
      "rows": 5
    },
    "fixed": [
      {
        "id": "q1",
        "kind": "quill",
        "x": 1,
        "y": 1
      },
      {
        "id": "r1",
        "kind": "resonator",
        "x": 7,
        "y": 1
      }
    ],
    "palette": {
      "fork": 2,
      "mould": 1,
      "damper": 1
    },
    "cases": [
      {
        "name": "Aria",
        "seeds": {
          "q1": "AABC"
        },
        "targets": {
          "r1": "C"
        }
      },
      {
        "name": "Encore",
        "seeds": {
          "q1": "ABBC"
        },
        "targets": {
          "r1": "C"
        }
      },
      {
        "name": "Coda",
        "seeds": {
          "q1": "BC"
        },
        "targets": {
          "r1": "C"
        }
      },
      {
        "name": "Reprise",
        "seeds": {
          "q1": "ABAC"
        },
        "targets": {
          "r1": "AC"
        }
      }
    ],
    "reference": {
      "parts": [
        {
          "id": "p0",
          "kind": "fork",
          "config": {
            "note": "A",
            "mode": "consume"
          },
          "x": 3,
          "y": 1
        },
        {
          "id": "p1",
          "kind": "fork",
          "config": {
            "note": "B",
            "mode": "consume"
          },
          "x": 5,
          "y": 1
        }
      ],
      "wires": [
        {
          "from": {
            "part": "q1",
            "port": "out"
          },
          "to": {
            "part": "p0",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "left"
          },
          "to": {
            "part": "p0",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "right"
          },
          "to": {
            "part": "p1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "left"
          },
          "to": {
            "part": "p1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "right"
          },
          "to": {
            "part": "r1",
            "port": "in"
          }
        }
      ]
    },
    "meta": {
      "minParts": 2,
      "signaturesAtMin": 1,
      "signaturesCapped": false,
      "forced": [
        "fork"
      ]
    },
    "walkthrough": [
      {
        "focus": "commission",
        "title": "IV · Wolf notes",
        "body": "A Tuning Fork in bite mode removes one matching lead marble. A loop can repeat this until the lead marble changes. Use one machine for all 4 performances. Each resonator must receive its target train; resonators marked “stay silent” must receive nothing."
      },
      {
        "focus": "board",
        "title": "A nudge",
        "body": "Use one bite loop for A, then send its non-matching output to a second bite loop for B. Check Reprise as well."
      }
    ]
  },
  {
    "id": "campaign-tangle-stamped-gate",
    "title": "Entanglement I: the stamped gate",
    "chapter": "V · Entanglements",
    "board": {
      "cols": 9,
      "rows": 7
    },
    "fixed": [
      {
        "id": "q1",
        "kind": "quill",
        "label": "the label",
        "x": 1,
        "y": 1
      },
      {
        "id": "q2",
        "kind": "quill",
        "label": "the payload",
        "x": 1,
        "y": 3
      },
      {
        "id": "r1",
        "kind": "resonator",
        "label": "spent labels",
        "x": 7,
        "y": 1
      },
      {
        "id": "r2",
        "kind": "resonator",
        "label": "hall of A",
        "x": 7,
        "y": 3
      },
      {
        "id": "r3",
        "kind": "resonator",
        "label": "hall of B",
        "x": 7,
        "y": 5
      }
    ],
    "palette": {
      "coupling": 1,
      "mould": 1,
      "damper": 1
    },
    "cases": [
      {
        "name": "Aria",
        "seeds": {
          "q1": "A",
          "q2": "CD"
        },
        "targets": {
          "r1": "A",
          "r2": "CDD"
        }
      },
      {
        "name": "Encore",
        "seeds": {
          "q1": "B",
          "q2": "CD"
        },
        "targets": {
          "r1": "B",
          "r3": "CD"
        }
      }
    ],
    "reference": {
      "parts": [
        {
          "id": "p0",
          "kind": "coupling",
          "config": {
            "noteA": "A",
            "noteB": "A"
          },
          "x": 3,
          "y": 1
        },
        {
          "id": "p1",
          "kind": "mould",
          "config": {
            "note": "D"
          },
          "x": 5,
          "y": 1
        }
      ],
      "wires": [
        {
          "from": {
            "part": "q1",
            "port": "out"
          },
          "to": {
            "part": "p0",
            "port": "inA"
          }
        },
        {
          "from": {
            "part": "q2",
            "port": "out"
          },
          "to": {
            "part": "p0",
            "port": "inB"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "outAR"
          },
          "to": {
            "part": "r1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "outBL"
          },
          "to": {
            "part": "p1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "outBR"
          },
          "to": {
            "part": "r3",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "out"
          },
          "to": {
            "part": "r2",
            "port": "in"
          }
        }
      ]
    },
    "meta": {
      "minParts": 2,
      "signaturesAtMin": 2,
      "signaturesCapped": true,
      "forced": [
        "coupling",
        "mould"
      ]
    },
    "walkthrough": [
      {
        "focus": "commission",
        "title": "V · Entanglements",
        "body": "A Coupling waits for two trains. Each train’s route is determined by the other train’s lead marble. Use one machine for all 2 performances. Each resonator must receive its target train; resonators marked “stay silent” must receive nothing."
      },
      {
        "focus": "board",
        "title": "A nudge",
        "body": "Connect the payload and label trains to opposite Coupling inputs. Each train is routed by the lead marble on the other train."
      }
    ]
  },
  {
    "id": "campaign-tangle-mutual",
    "title": "Entanglement II: mutual regard",
    "chapter": "V · Entanglements",
    "board": {
      "cols": 9,
      "rows": 9
    },
    "fixed": [
      {
        "id": "q1",
        "kind": "quill",
        "label": "first voice",
        "x": 1,
        "y": 1
      },
      {
        "id": "q2",
        "kind": "quill",
        "label": "second voice",
        "x": 1,
        "y": 3
      },
      {
        "id": "r1",
        "kind": "resonator",
        "label": "first hall",
        "x": 5,
        "y": 1
      },
      {
        "id": "r2",
        "kind": "resonator",
        "label": "first annex",
        "x": 5,
        "y": 3
      },
      {
        "id": "r3",
        "kind": "resonator",
        "label": "second hall",
        "x": 5,
        "y": 5
      },
      {
        "id": "r4",
        "kind": "resonator",
        "label": "second annex",
        "x": 5,
        "y": 7
      }
    ],
    "palette": {
      "coupling": 1,
      "mould": 1,
      "damper": 1
    },
    "cases": [
      {
        "name": "Aria",
        "seeds": {
          "q1": "AB",
          "q2": "AD"
        },
        "targets": {
          "r1": "AB",
          "r3": "AD"
        }
      },
      {
        "name": "Encore",
        "seeds": {
          "q1": "BB",
          "q2": "AD"
        },
        "targets": {
          "r1": "BB",
          "r4": "AD"
        }
      },
      {
        "name": "Coda",
        "seeds": {
          "q1": "BD",
          "q2": "CB"
        },
        "targets": {
          "r2": "BD",
          "r4": "CB"
        }
      }
    ],
    "reference": {
      "parts": [
        {
          "id": "p0",
          "kind": "coupling",
          "config": {
            "noteA": "A",
            "noteB": "A"
          },
          "x": 3,
          "y": 1
        }
      ],
      "wires": [
        {
          "from": {
            "part": "q1",
            "port": "out"
          },
          "to": {
            "part": "p0",
            "port": "inA"
          }
        },
        {
          "from": {
            "part": "q2",
            "port": "out"
          },
          "to": {
            "part": "p0",
            "port": "inB"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "outAL"
          },
          "to": {
            "part": "r1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "outAR"
          },
          "to": {
            "part": "r2",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "outBL"
          },
          "to": {
            "part": "r3",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "outBR"
          },
          "to": {
            "part": "r4",
            "port": "in"
          }
        }
      ]
    },
    "meta": {
      "minParts": 1,
      "signaturesAtMin": 8,
      "signaturesCapped": false,
      "forced": [
        "coupling"
      ]
    },
    "walkthrough": [
      {
        "focus": "commission",
        "title": "V · Entanglements",
        "body": "A Coupling waits for two trains. Each train’s route is determined by the other train’s lead marble. Use one machine for all 3 performances. Each resonator must receive its target train; resonators marked “stay silent” must receive nothing."
      },
      {
        "focus": "board",
        "title": "A nudge",
        "body": "Set both Coupling matches, then trace one performance through all four outputs."
      }
    ]
  },
  {
    "id": "campaign-tempo-cross",
    "title": "Tempo II: the crossed duet",
    "chapter": "VI · Tempo",
    "board": {
      "cols": 9,
      "rows": 9
    },
    "fixed": [
      {
        "id": "q1",
        "kind": "quill",
        "label": "B: near",
        "x": 1,
        "y": 1
      },
      {
        "id": "q2",
        "kind": "quill",
        "label": "A: far",
        "x": 1,
        "y": 3
      },
      {
        "id": "q3",
        "kind": "quill",
        "label": "near tail",
        "x": 1,
        "y": 5
      },
      {
        "id": "q4",
        "kind": "quill",
        "label": "far tail",
        "x": 1,
        "y": 7
      },
      {
        "id": "r1",
        "kind": "resonator",
        "label": "hall of A",
        "x": 7,
        "y": 1
      },
      {
        "id": "r2",
        "kind": "resonator",
        "label": "the other hall",
        "x": 7,
        "y": 3
      }
    ],
    "palette": {
      "valve": 1,
      "unison": 1,
      "fork": 1
    },
    "cases": [
      {
        "name": "Aria",
        "seeds": {
          "q1": "B",
          "q2": "A",
          "q3": "C",
          "q4": "D"
        },
        "targets": {
          "r1": "AC",
          "r2": "BD"
        }
      },
      {
        "name": "Encore",
        "seeds": {
          "q1": "B",
          "q2": "A",
          "q3": "D",
          "q4": "C"
        },
        "targets": {
          "r1": "AD",
          "r2": "BC"
        }
      }
    ],
    "reference": {
      "parts": [
        {
          "id": "p0",
          "kind": "valve",
          "config": {
            "delay": 1
          },
          "x": 3,
          "y": 1
        },
        {
          "id": "p1",
          "kind": "unison",
          "config": {},
          "x": 3,
          "y": 3
        },
        {
          "id": "p2",
          "kind": "fork",
          "config": {
            "note": "A",
            "mode": "peek"
          },
          "x": 5,
          "y": 1
        }
      ],
      "wires": [
        {
          "from": {
            "part": "q1",
            "port": "out"
          },
          "to": {
            "part": "p0",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "q2",
            "port": "out"
          },
          "to": {
            "part": "p1",
            "port": "lead"
          }
        },
        {
          "from": {
            "part": "q3",
            "port": "out"
          },
          "to": {
            "part": "p1",
            "port": "tail"
          }
        },
        {
          "from": {
            "part": "q4",
            "port": "out"
          },
          "to": {
            "part": "p1",
            "port": "tail"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "out"
          },
          "to": {
            "part": "p1",
            "port": "lead"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "out"
          },
          "to": {
            "part": "p2",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p2",
            "port": "left"
          },
          "to": {
            "part": "r1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p2",
            "port": "right"
          },
          "to": {
            "part": "r2",
            "port": "in"
          }
        }
      ]
    },
    "meta": {
      "minParts": 3,
      "signaturesAtMin": 6,
      "signaturesCapped": true,
      "forced": [
        "unison",
        "fork"
      ],
      "valveAtLayout": true
    },
    "walkthrough": [
      {
        "focus": "commission",
        "title": "VI · Tempo",
        "body": "Track length sets travel time. A Valve adds a selected delay before passing the train through unchanged. Use one machine for all 2 performances. Each resonator must receive its target train; resonators marked “stay silent” must receive nothing."
      },
      {
        "focus": "board",
        "title": "A nudge",
        "body": "Run without a valve and check the event log. Then delay the one path that arrives too early."
      }
    ]
  },
  {
    "id": "campaign-concerto-envelope",
    "title": "Concerto I: the envelope",
    "chapter": "VII · Concerto",
    "board": {
      "cols": 9,
      "rows": 7
    },
    "fixed": [
      {
        "id": "q1",
        "kind": "quill",
        "x": 1,
        "y": 1
      },
      {
        "id": "r1",
        "kind": "resonator",
        "label": "spent headers",
        "x": 7,
        "y": 1
      },
      {
        "id": "r2",
        "kind": "resonator",
        "label": "hall of A",
        "x": 7,
        "y": 3
      },
      {
        "id": "r3",
        "kind": "resonator",
        "label": "hall of B",
        "x": 7,
        "y": 5
      }
    ],
    "palette": {
      "splitter": 1,
      "coupling": 1,
      "mould": 1,
      "damper": 1
    },
    "cases": [
      {
        "name": "Aria",
        "seeds": {
          "q1": "ACD"
        },
        "targets": {
          "r1": "A",
          "r2": "CD"
        }
      },
      {
        "name": "Encore",
        "seeds": {
          "q1": "BCD"
        },
        "targets": {
          "r1": "B",
          "r3": "CD"
        }
      },
      {
        "name": "Coda",
        "seeds": {
          "q1": "ADD"
        },
        "targets": {
          "r1": "A",
          "r2": "DD"
        }
      }
    ],
    "reference": {
      "parts": [
        {
          "id": "p0",
          "kind": "splitter",
          "config": {
            "k": 1
          },
          "x": 3,
          "y": 1
        },
        {
          "id": "p1",
          "kind": "coupling",
          "config": {
            "noteA": "A",
            "noteB": "A"
          },
          "x": 5,
          "y": 1
        }
      ],
      "wires": [
        {
          "from": {
            "part": "q1",
            "port": "out"
          },
          "to": {
            "part": "p0",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "head"
          },
          "to": {
            "part": "p1",
            "port": "inA"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "rest"
          },
          "to": {
            "part": "p1",
            "port": "inB"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "outAR"
          },
          "to": {
            "part": "r1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "outBL"
          },
          "to": {
            "part": "r2",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "outBR"
          },
          "to": {
            "part": "r3",
            "port": "in"
          }
        }
      ]
    },
    "meta": {
      "minParts": 2,
      "signaturesAtMin": 8,
      "signaturesCapped": true,
      "forced": [
        "splitter",
        "coupling"
      ]
    },
    "walkthrough": [
      {
        "focus": "commission",
        "title": "VII · Concerto",
        "body": "These levels combine splitting, joining, routing, loops, and cross-routing. Use one machine for all 3 performances. Each resonator must receive its target train; resonators marked “stay silent” must receive nothing."
      },
      {
        "focus": "board",
        "title": "A nudge",
        "body": "Split after one marble, then connect the two trains to opposite Coupling inputs."
      }
    ]
  },
  {
    "id": "campaign-concerto-signed",
    "title": "Concerto II: the signed envelope",
    "chapter": "VII · Concerto",
    "board": {
      "cols": 11,
      "rows": 7
    },
    "fixed": [
      {
        "id": "q1",
        "kind": "quill",
        "x": 1,
        "y": 1
      },
      {
        "id": "r1",
        "kind": "resonator",
        "label": "spent headers",
        "x": 9,
        "y": 1
      },
      {
        "id": "r2",
        "kind": "resonator",
        "label": "hall of A",
        "x": 9,
        "y": 3
      },
      {
        "id": "r3",
        "kind": "resonator",
        "label": "hall of B",
        "x": 9,
        "y": 5
      }
    ],
    "palette": {
      "splitter": 1,
      "coupling": 1,
      "mould": 1
    },
    "cases": [
      {
        "name": "Aria",
        "seeds": {
          "q1": "ACD"
        },
        "targets": {
          "r1": "A",
          "r2": "CDA"
        }
      },
      {
        "name": "Encore",
        "seeds": {
          "q1": "BCD"
        },
        "targets": {
          "r1": "B",
          "r3": "CD"
        }
      },
      {
        "name": "Coda",
        "seeds": {
          "q1": "ADC"
        },
        "targets": {
          "r1": "A",
          "r2": "DCA"
        }
      }
    ],
    "reference": {
      "parts": [
        {
          "id": "p0",
          "kind": "splitter",
          "config": {
            "k": 1
          },
          "x": 3,
          "y": 1
        },
        {
          "id": "p1",
          "kind": "coupling",
          "config": {
            "noteA": "A",
            "noteB": "A"
          },
          "x": 5,
          "y": 1
        },
        {
          "id": "p2",
          "kind": "mould",
          "config": {
            "note": "A"
          },
          "x": 7,
          "y": 1
        }
      ],
      "wires": [
        {
          "from": {
            "part": "q1",
            "port": "out"
          },
          "to": {
            "part": "p0",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "head"
          },
          "to": {
            "part": "p1",
            "port": "inA"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "rest"
          },
          "to": {
            "part": "p1",
            "port": "inB"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "outAR"
          },
          "to": {
            "part": "r1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "outBL"
          },
          "to": {
            "part": "p2",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "outBR"
          },
          "to": {
            "part": "r3",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p2",
            "port": "out"
          },
          "to": {
            "part": "r2",
            "port": "in"
          }
        }
      ]
    },
    "meta": {
      "minParts": 3,
      "signaturesAtMin": 8,
      "signaturesCapped": true,
      "forced": [
        "splitter",
        "coupling",
        "mould"
      ]
    },
    "walkthrough": [
      {
        "focus": "commission",
        "title": "VII · Concerto",
        "body": "These levels combine splitting, joining, routing, loops, and cross-routing. Use one machine for all 3 performances. Each resonator must receive its target train; resonators marked “stay silent” must receive nothing."
      },
      {
        "focus": "board",
        "title": "A nudge",
        "body": "Route the body first, then place the mould only on the hall-of-A output."
      }
    ]
  },
  {
    "id": "campaign-concerto-wolf",
    "title": "Concerto III: the wolf’s commission",
    "chapter": "VII · Concerto",
    "board": {
      "cols": 11,
      "rows": 5
    },
    "fixed": [
      {
        "id": "q1",
        "kind": "quill",
        "x": 1,
        "y": 1
      },
      {
        "id": "r1",
        "kind": "resonator",
        "label": "hall of B",
        "x": 9,
        "y": 1
      },
      {
        "id": "r2",
        "kind": "resonator",
        "label": "hall of C",
        "x": 9,
        "y": 3
      }
    ],
    "palette": {
      "fork": 2,
      "mould": 2
    },
    "cases": [
      {
        "name": "Aria",
        "seeds": {
          "q1": "AABC"
        },
        "targets": {
          "r1": "BCC"
        }
      },
      {
        "name": "Encore",
        "seeds": {
          "q1": "ACB"
        },
        "targets": {
          "r2": "CBB"
        }
      },
      {
        "name": "Coda",
        "seeds": {
          "q1": "BC"
        },
        "targets": {
          "r1": "BCC"
        }
      },
      {
        "name": "Reprise",
        "seeds": {
          "q1": "CB"
        },
        "targets": {
          "r2": "CBB"
        }
      }
    ],
    "reference": {
      "parts": [
        {
          "id": "p0",
          "kind": "fork",
          "config": {
            "note": "A",
            "mode": "consume"
          },
          "x": 3,
          "y": 1
        },
        {
          "id": "p1",
          "kind": "fork",
          "config": {
            "note": "B",
            "mode": "peek"
          },
          "x": 5,
          "y": 1
        },
        {
          "id": "p2",
          "kind": "mould",
          "config": {
            "note": "B"
          },
          "x": 7,
          "y": 1
        },
        {
          "id": "p3",
          "kind": "mould",
          "config": {
            "note": "C"
          },
          "x": 7,
          "y": 3
        }
      ],
      "wires": [
        {
          "from": {
            "part": "q1",
            "port": "out"
          },
          "to": {
            "part": "p0",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "left"
          },
          "to": {
            "part": "p0",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p0",
            "port": "right"
          },
          "to": {
            "part": "p1",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "left"
          },
          "to": {
            "part": "p3",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p1",
            "port": "right"
          },
          "to": {
            "part": "p2",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p2",
            "port": "out"
          },
          "to": {
            "part": "r2",
            "port": "in"
          }
        },
        {
          "from": {
            "part": "p3",
            "port": "out"
          },
          "to": {
            "part": "r1",
            "port": "in"
          }
        }
      ]
    },
    "meta": {
      "minParts": 4,
      "signaturesAtMin": 4,
      "signaturesCapped": false,
      "forced": [
        "fork",
        "mould"
      ]
    },
    "walkthrough": [
      {
        "focus": "commission",
        "title": "VII · Concerto",
        "body": "These levels combine splitting, joining, routing, loops, and cross-routing. Use one machine for all 4 performances. Each resonator must receive its target train; resonators marked “stay silent” must receive nothing."
      },
      {
        "focus": "board",
        "title": "A nudge",
        "body": "Remove A marbles in a loop, route the resulting train once, then place the correct Mould on each output path."
      }
    ]
  },
];
